### ISSUE TITLE
All Spacer fields displayed first, not in order

### ISSUE THREAD

**Issue by cd13sr** [getgrav/grav-plugin-form#104]
When adding multiple Spacer field types to a page form, they are all being displayed first on the site and not in the order specified in the page's front-matter.

For example, these are the field types specified in the front-matter:

Spacer
Text
Text
Spacer
Text
Text

I would expect that same order when the form is rendered on the page, however, those two Spacer fields are being displayed at the top, before all the text fields.

Thanks.

**Comment by WeAreELIC** [comment]
FYI, this may help. In the plugin file: form > classes > form.php

Changing the unset function to an array_splice on line 201 fixed the issue for me.

**Current lines 200-203**
```
if (is_numeric($key) && isset($field['name'])) {
    unset($this->items['fields'][$key]);
    $key = $field['name'];
}
```

**Update**
```
if (is_numeric($key) && isset($field['name'])) {
    array_splice($this->items['fields'], $key);
    $key = $field['name'];
}
```

Thanks.

**Comment by flaviocopes** [comment]
Replicated

**Comment by flaviocopes** [comment]
@WeAreELIC your proposed solution seems to work for me too. Committing 👍
