### ISSUE TITLE
Can't have forms with identical names on two different pages

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-form#107]
I had a setup where two different pages both had defined one form each, but with an identical name. This caused an issue where I could submit the form and be redirected back to the same page, but the form object would be constructed from the other page.

Reproducing this issue was pretty simple for me, but let me know if you need more details.

**Comment by flaviocopes** [comment]
After asking @rhukster, it's expected. Forms must have a unique name. Maybe there should be a more explicit way to detect the problem (Grav should raise an error?)

**Comment by fredrikekelund** [comment]
I can understand how they would need to have a locally unique name, but why would they need a globally unique name? The form is submitted to a single page. Granted, that page could have multiple forms, but it doesn't make much sense to load forms from all pages if I'm targeting just one page. Right?

**Comment by rhukster** [comment]
The way forms works in Forms 2.0, is that all forms are gathered up and cached based on the form name.  This allows you to access any form from any page (including modular pages) and addresses a huge issue with the Forms 1.0 release.  this is the reason why names can conflict and this is documented:

![2016-11-22 at 9 52 am](https://cloud.githubusercontent.com/assets/1084697/20536554/be57e646-b0a6-11e6-866c-29119b414528.png)

**Comment by fredrikekelund** [comment]
So I guess the idea here is for instance to be able to add eg. a contact form to the footer of a site and use a single template to generate the controls for that form? I don't know how common that use case is, but it would make more sense if I always had to qualify the name of the form with the route of the page where it lives. Basically as shown in the docs the last example under "Displaying Forms from Twig", but including a form name as well. Does it work to pass both a route and a name to the `forms` function in Twig templates?

But really, the main issue here is **form submissions**. Why do we need to look for the form from a global pool of forms when we handle a form submission?

**Comment by rhukster** [comment]
The form name is passed as a hidden field in the form, this is the name that is used to look up the form in order to process it.

**Comment by fredrikekelund** [comment]
Yes, I know, and that's totally fine! I'm not trying to be hostile, it's just that the issue I encountered with my form submissions effectively being "processed on a different page" than the one it was submitted to was pretty puzzling to me (and I bet you would have found it equally puzzling).

I'm just wondering - is there a use case where it's necessary to look through a global pool of forms when parsing form submissions? If not, maybe we can change the behavior there?

**Comment by rhukster** [comment]
Yes, this functionality is how modular forms is able to work, as well as having a common form in say the footer, that can be processed anywhere.

**Comment by fredrikekelund** [comment]
Well, I guess that the modular page use case doesn't require all pages to be scanned, but rather just the current page and it's children?

As for the contact form that can be processed anywhere, the processed form object isn't passed to the page that sent the submission in any case. So even if it's convenient to be able to submit the same form to any page (even if it maybe isn't the most logical solution), I wasn't able to retrieve the form message in the page template of the submitter page, so long as the form submission was handled by a different page. 

I can have a deeper look into the logic here and come back with some more concrete suggestions, but if nothing else, then not getting ahold of `form.message` was my major issue with this logic. Do you think we can try to change that behavior somehow, @rhukster?

**Comment by rhukster** [comment]
I think this has been answered.  Grav process ALL pages during onPageProcessed and parses forms.. any duplicate named forms will be overwritten if another form with the same name is found.  

Ensure all forms are unique.  That's the rule :)
