### ISSUE TITLE
"Cannot use Grav\Plugin\Admin as Admin because the name is already in use"

### ISSUE THREAD

**Issue by btcyg** [getgrav/grav-plugin-form#108]
Dear all, 

I just ran a plugin update. All them perfectly successfully updated except one: form.
I am told: 
> "Package(s) successfully updated." 

but in the meantime, I have the attached warning briefly showing up on the upright part of the screen indicating me the following: 

> "Cannot use Grav\Plugin\Admin as Admin because the name is already in use"

What would you suggest, as I am beginning of Grav, and as the learn.getgrav does not seem to provide any answer for that?

![capture d ecran 2016-11-22 a 15 33 01 2](https://cloud.githubusercontent.com/assets/23529340/20528061/025b48aa-b0cb-11e6-8688-055f6cb4c9e5.png)

Many thanks in advance for your feedback.

Best regards, 

B.

**Comment by flaviocopes** [comment]
Hi @btcyg I cannot replicate the problem. Can you PM me your user/ folder at https://gitter.im/flaviocopes so I can try with your same files?

**Comment by flaviocopes** [comment]
Thanks for reporting and posting your user folder, got it. I fixed this problem in https://github.com/getgrav/grav-plugin-admin/commit/a8d8b048bd954c14d2f3c9b90075ca3f6871d035
