### ISSUE TITLE
Element order

### ISSUE THREAD

**Issue by jhautefeuille** [getgrav/grav-plugin-form#109]
Hi,

When we try a form a mix with spacer and text, order element are wrong.

Ex : 
Spacer
Text
Text
Spacer
Text
Text

Give a print form like

Spacer
Spacer
Text
Text
Text
Text

Several users had issue like https://getgrav.org/forum#!/plugin-development ((Front-end) form spacer fields displayed first, not in order).

Thank you.

**Comment by flaviocopes** [comment]
Got the same issue yesterday (https://github.com/getgrav/grav-plugin-form/issues/104) and I added a commit that fixed it, if you can check that the solution works for you.
