### ISSUE TITLE
Form doesnt work since Multi language enabled

### ISSUE THREAD

**Issue by nenosw** [getgrav/grav-plugin-form#111]
Hi

I have a form that stopped working since multilanguage was enabled. The contact page just refreshes on 'send' and doesn't send any mails or save to the data folder. I updated the plugin and checked if the #95 fix was in there, it still does not work. 

I dont know if im missing something in the configuration.

Please help

**Comment by flaviocopes** [comment]
Can you paste your form definition?

**Comment by TeslaBargain** [comment]
I am experiencing the very same issue, maybe the OP can elaborate more details?

**Comment by TeslaBargain** [comment]
Exceptional, @flaviocopes already found the solution to that problem by setting `redirect_trailing_slash: false`

**Comment by out-of-order** [comment]
Thanks for the hint. I will test it.
I have the same problem though I use only one language, but which I had manually set at the configuration settings in the admin backend.

**Comment by rhukster** [comment]
Is this still an issue? There were several forms fixed this past month that could resolve this issue.

**Comment by TeslaBargain** [comment]
@rhukster I don't know if any of the applied fixes changed anything, for me it has already been working again since @flaviocopes told me to set `redirect_trailing_slash: false` and I did not change any settings any more since then.

**Comment by flaviocopes** [comment]
Closing, comment if anyone still got the problem
