### ISSUE TITLE
Checkboxes validation requires all boxes checked to validate

### ISSUE THREAD

**Issue by gittygritty** [getgrav/grav-plugin-form#112]
If validate required is true, you have to check all checkboxes to pass validation. Should only require one checked to pass validation.

**Comment by rhukster** [comment]
Looked into this, but there's really no way to do it with HTML5.  You have to use Javascript to create a dynamic checkbox group.  This might be helpful: http://afarkas.github.io/webshim/demos/demos/forms.html#Custom-validity
