### ISSUE TITLE
form-nonce id with multiple forms.

### ISSUE THREAD

**Issue by david-bettondesign** [getgrav/grav-plugin-form#115]
Regarding forum post: https://getgrav.org/forum#!/plugin-development:form-nonce-on-multiple-form
The page does not pass html validation when more than one form is displayed on a page. This is because each form contains a hidden input of `<input type="hidden" id="form-nonce" name="form-nonce" value="********" />`.
ID's must be unique and therefore the id of `form-nonce` breaks validation as it appears more than once.

**Comment by rhukster** [comment]
Yes, technically that's not valid according to HTML specs, however it does still work and doesn't effect functionality.  We'll get this sorted soon.
