### ISSUE TITLE
Allow streams in `file` field widget

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav-plugin-form#119]
The [file field widget](https://learn.getgrav.org/forms/forms/fields-available#the-file-field) only supports `@self`, `@page:/route` or `local/rel/path/` as destination paths.

Currently, it is not possible to use streams, i.e., `user://uploads`. Using streams would help uncouple plugins from the actual folder structure.

**Comment by rhukster** [comment]
PR welcome 👍

**Comment by mahagr** [comment]
Implemented in 3.0
