### ISSUE TITLE
Trim fields before validation

### ISSUE THREAD

**Issue by z38** [getgrav/grav-plugin-form#12]
Currently, `Grav\Common\Data\Validation` accepts field values which only consist of spaces and have the option `required`. Is this the intended behaviour or should this be fixed?

**Comment by flaviocopes** [comment]
@rhukster should we `trim()` first thing in Validation::validate()?

**Comment by rhukster** [comment]
Trim within validate is fine.  There are cases when empty strings are intended (obviously not with `required`), but needs to be ok in both cases.

**Comment by Sommerregen** [comment]
I think rather than putting trim in validation we should better put `trim` here https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Data/Validation.php#L589-L592 with the body

```php
if (is_string($value)) {
  $value = trim($value);
}
return (bool) $params !== true || !empty($value);
```

**Comment by z38** [comment]
I justed updated the form plugin to the master branch. The field values are trimmed, thank you!
