### ISSUE TITLE
Tooltip popups not included in language.yaml

### ISSUE THREAD

**Issue by rkammann** [getgrav/grav-plugin-form#120]
The form plugin creates a number of tooltip popups in English. Those do not appear in the language.yaml file, making them hard to translate for non-English sites. Could those items be included in language.yaml?

**Comment by flaviocopes** [comment]
You mean in Admin, or in your frontend form?

**Comment by rkammann** [comment]
I'm fine with any amount of English in the admin interface, but I'd like to have the front-end fully translated, without any English in it. The form plugin's language.yaml file does not include the strings that  appear in form tooltip popups, so I assume I'd have to edit those in the raw PHP, which I'm trying to avoid.

**Comment by flaviocopes** [comment]
Admin is fully translatable. If you set your language in the user settings inside Admin, you should have everything translated, assuming all the strings were added by the translation team (managed in https://crowdin.com/project/grav-admin). If there are english strings which should be translated, let us know. 

On the other hand, the frontend is fully customizable. There are no fixed strings, and the Form plugin will show what you defined in the form itself.

**Comment by rkammann** [comment]
Thanks! I checked the form definition again, and there were no form tooltip strings defined there. Then I checked the front-end form in two different browsers and noticed that the wording of the tooltips differed ('Please fill in this field.' vs 'Please enter an email address', for instance.)  This strongly suggests that it's the browser filling in the tooltip, and that a reader with a browser that (unlike my own) defaults to the non-English language in question, will see a corresponding tooltip in that language. 

So, my mistake for raising this: sorry, and please ignore!

**Comment by flaviocopes** [comment]
Oh ok, I was thinking about the form field description, like the ones that appear in Admin when hovering with the mouse. 

Yes, the client-side validation is a browser feature, the language will depend on the system/browser language.
