### ISSUE TITLE
Set Form fields defaults from plugin

### ISSUE THREAD

**Issue by jacmgr** [getgrav/grav-plugin-form#123]
I asked this question over on the forum and flaviocopes suggested to post here and suggest a way to do it!  I am not smart enough to suggest how to do it; but will try any ideas presented! 

Here is the question:
I have a simple front end contact form and added another field for text input. The form is completely defined in the frontmatter and operates as shown in the grav documentation. I want to use a plugin to prefill that added field dynamically to a variety of things. I am able in the form definition to set a “default” value, but that is not dynamic. In my plugin, what event would I use to get access to the form field parameters and re-set the default value before the form is displayed? So a more general question I guess: How to use a plugin to dynamically set default values of form fields before form is displayed?

(I looked at login plugin forms; I figured it is similar since it adds its own formfields...but I was not capable enough to see how it does what I need).

**Comment by jacmgr** [comment]
OK. Would be a nice enhancement!  I have a workaround for my current case.

In the form definition use a default attribute like this:
 ```
  - name: summary
      type: text
      default: ByPlugin.summary    #any unique word or phrase as a placeholder.
```
Then in plugin 
````
    public function onOutputGenerated()
    {
        $DV = some function or process to get desired default value
        $this->grav->output = str_replace('ByPlugin.summary', $DV, $this->grav->output);  
     }
````
Probably only works on text/textareas, but that is all i needed.

**Comment by flaviocopes** [comment]
Nice workaround!

**Comment by Nebel54** [comment]
If i'm not mistaken you should be able to set default values dynamically with function calls (via data-options@), documented here: https://learn.getgrav.org/forms/blueprints/advanced-features#using-function-calls-data

**Comment by mahagr** [comment]
Closing as this is already possible (in multiple ways).

**Comment by Bahvya-Dev** [comment]
I have used the form plugin in quark theme in grav and follow the instructions mentioned in the documentation https://learn.getgrav.org/16/forms/forms but my form form is not displaying. It looks like this http://prntscr.com/u4r67l

Please let me know how can I fix this issue.
