### ISSUE TITLE
fieldset support

### ISSUE THREAD

**Issue by bobbwal** [getgrav/grav-plugin-form#125]
Does this plugin support fieldsets or anyway of grouping fields? It doesn't appear to but maybe I'm missing something.

Thanks

**Comment by flaviocopes** [comment]
Interesting, I just noticed we miss such functionality. Marking as enhancement.

**Comment by jraack** [comment]
Hi Guys,

I just found an issue with the fieldset. I have a form based on the fields syntax.
When i add fields under a fieldset it is not validating my input fields if they are required?

Or do i missing something?

Best,
Joe
