### ISSUE TITLE
Duplicated ID "form-nonce" on page with two form

### ISSUE THREAD

**Issue by DavideTrendstudio** [getgrav/grav-plugin-form#128]
I have two forms on a page in my website (request form + newsletter form in footer)
The first form is defined directly inside the page's frontmatter and rendered by the form.html.twig template.
The second form is present on each page of the website in the footer, so I defined it inside a non-visible and non-routable page and import it in every page of the website using the 'include' function  in the base.html.twig template.

The Form Plugin generates the hidden "form-nonce" input field for every form and sets id="form-nonce" and name="form-nonce", so my page is not valid due to duplicated IDs.

My question is: is there the possibility to set the id and the name of a form nonce inside the frontmatter of a page and override the default values? Is my approach with the newsletter form incorrect?

**Comment by rhukster** [comment]
Duplicate: https://github.com/getgrav/grav-plugin-form/issues/115

Already fixed for next release.
