### ISSUE TITLE
Retrieve page objects

### ISSUE THREAD

**Issue by GittiHab** [getgrav/grav-plugin-form#129]
Hello,
I am using the field type `pages` to select pages in a pages blueprint. In the twig-Template I then try to retrieve the stored pages but all I get is the slug of the page – how can I store something useful so I can retrieve the actual page object in the theme?

It would be super helpful if someone could help me here...

**Comment by rhukster** [comment]
All you need is the route, then you can use `page.find()` to get the actual page.  https://learn.getgrav.org/content/content-pages#finding-other-pages

**Comment by GittiHab** [comment]
@rhukster Great, thank you! I have been looking in the Sites API for `Pages` but this was obviously the wrong place.
