### ISSUE TITLE
Input of type='number' does not accept validate.min: 0 and validate.max: 0

### ISSUE THREAD

**Issue by DavideTrendstudio** [getgrav/grav-plugin-form#130]
Setting the validate.min value to 0 does not work. The attribute 'min' does not appear in the html tag.

Example:
                name: field
                label: 'example field'
                placeholder: 1
                type: number
                validate: { required: true, min: 0, max: 10 }

Setting 'min' to any other value works perfectly.

The same happens with 'validate.max: 0'.

**Comment by rhukster** [comment]
Hmm I think the 0 is being treated as false. Will check.
