### ISSUE TITLE
[question] Invisible reCAPTCHA

### ISSUE THREAD

**Issue by zachkont** [getgrav/grav-plugin-form#132]
Do you plan to support the invisible ReCaptcha any time soon? It'd be great

**Comment by rhukster** [comment]
This is quite a bit different from the 'old' recaptcha so we'll need to investigate how best to implement it.

**Comment by zachkont** [comment]
Ok, thanks for the reply

**Comment by diegovogel** [comment]
@rhukster Any update on support for Invisible reCAPTCHA? Or instructions on how to get it to work with existing Grav Forms plugin? 
Using Invisible reCAPTCHA would be a big plus from a UX/aesthetics perspective. I looked through reCAPTCHA docs but don't know enough to make it work. Thanks!

**Comment by Sergiop79** [comment]
Also someone created a tool to break reCaptcha, https://github.com/eastee/rebreakcaptcha

is there another secure method to block spam in grav forms?. I implemented reCaptcha with some honeypot fields and still receiving spam.

Thanks

**Comment by sjclark** [comment]
This would be a fantastic addition to Grav Forms 👍

**Comment by mahagr** [comment]
reCAPTCHA v3 has been implemented to Form 3.0, @w00fz did we add support for this too?

**Comment by w00fz** [comment]
Yes, we added support for reCaptcha 3.

**Comment by Sergiop79** [comment]
How can we implement reCaptcha 3 on a contact from?

**Comment by w00fz** [comment]
You need the beta version of form, 3.0.
Then you can configure form to use reCaptcha 3 via admin for simplicity or manually.

**Comment by tim-bradley** [comment]
> You need the beta version of form, 3.0.
> Then you can configure form to use reCaptcha 3 via admin for simplicity or manually.

Ahhh. That's my problem. Any idea of general release timeframe?
