### ISSUE TITLE
how does one add class to fields?

### ISSUE THREAD

**Issue by Muphet** [getgrav/grav-plugin-form#133]
How do one can add class to each field to style form? i.e. with bootstrap

**Comment by rhukster** [comment]
https://learn.getgrav.org/forms/forms/form-options#classes

**Comment by matt-harris** [comment]
Please add `outerclasses:`, `wrapper_classes:`, `classes:` to documentation link you posted above. 

Thanks

**Comment by Sogl** [comment]
`wrapper_classes` still missing in docs 🤔
