### ISSUE TITLE
[question] about new conditional field

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-form#134]
could you provide a example how to use the new conditional field ?
Thanks

**Comment by rhukster** [comment]
https://gist.github.com/rhukster/7e83c40e906e92a5acf91a80303c034d

Where 'id' is a twig variable available in the form.  If true, the fields under the conditional will render.

I know this needs to be documented, it's listed here: https://github.com/getgrav/grav-learn/issues/356

**Comment by dimitrilongo** [comment]
thank you so much

**Comment by dimitrilongo** [comment]
conditional fields works only on form frontend ?
