### ISSUE TITLE
New outer div around buttons breaks layout after upgrade

### ISSUE THREAD

**Issue by WeAreELIC** [getgrav/grav-plugin-form#135]
I noticed that after upgrading the /user/plugins/form/templates/forms/default/form.html.twig template added an outer div around the buttons with an "outerclasses" attribute. This is great, however, it breaks my inline buttons and drops them to a new line, because of the outer divs.

I would maybe suggest to check for the outerclasses attribute, and if not defined, hide the outer divs too.

Thanks.

**Comment by rhukster** [comment]
Fixed, and released as 2.3.1

**Comment by WeAreELIC** [comment]
Awesome, nice work Andy!
