### ISSUE TITLE
Unwanted showing of number of fields when using Display field

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav-plugin-form#137]
When the `label` attribute of a field of type `display` is missing or is empty (`label: ''`) then the number of fields before the Display field is included in the HTML of the form and visible preceding the `content` attribute text.
The number can also be some internal field count number, assuming counting starts at zero.

I could not find where in the code or a template this number is output.

This is a part of the HTML of the form:
```
    <div class="form-field  ">
                                    <div class="form-label">
                    <label class="inline"  >
                                                                    9
                                                
                                        </label>
                </div>
                        <div class="form-data"
                                data-grav-field="display"
                data-grav-disabled="true"
                data-grav-default="null"
                            >
```

**Comment by rhukster** [comment]
Try `label: false`
