### ISSUE TITLE
Untranslated text keys showing up around my form

### ISSUE THREAD

**Issue by mn113** [getgrav/grav-plugin-form#138]
I'm having an issue with the custom text keys printing to the page around my form.

For example, instead of printing "Error validating the Captcha", it literally prints "PLUGIN_FORM.ERROR_VALIDATING_CAPTCHA".
Same thing with FORM.VALIDATION_FAIL and FORM.INVALID_INPUT messages (when I trigger those with my input).

This is not a i18n problem; my site is only in English. I can see that one of these keys is coming from `plugins/form/form.php` and one from `system/src/Grav/Common/Data/ValidationException.php`, but have no idea why the `translate` method is not looking them up from where they are defined in `system/languages/en.yaml` or `plugins/form/languages.yaml`.

Has anybody experienced this and could point me in the right direction?

My Grav is at 1.1.17 and Form is at 2.3.1

**Comment by flaviocopes** [comment]
Are translations enabled in your system configuration? By default it's enabled. Look at `system.languages.translations` in your system.yaml

**Comment by rhukster** [comment]
Closing because due to issue age.  Please re-open if you continue to have issues
