### ISSUE TITLE
Form + Mail Plugin dont work after update from 2.3.1 to 2.5.0

### ISSUE THREAD

**Issue by Necrosd** [getgrav/grav-plugin-form#146]
Hi Folks,

i use the agency skeleton with the integrated form and mail plugins. It worked fine until i updated the form Plugin from 2.3.1 to 2.5.0. The Fields are shown correctly and i see the correct post request, but it never find its way to the mail plugin (or maybe it stucks at a earlier point). 

Do i have to do changes or did i found a bug?

Hope u can help me, thx.

PS if it is important, the site with the problem is www.austenit-band.de

Eric

**Comment by flaviocopes** [comment]
Can you post your form definition?

**Comment by Necrosd** [comment]
Sure:

form:
    name: kontakt
    action: /home#kontakt
    fields:
        - name: name
          label: Name
          classes: form-control
          placeholder: Name
          autofocus: off
          autocomplete: on
          type: text
          position: right
          validate:
            required: true

        - name: email
          label: Email
          classes: form-control
          placeholder: E-Mail Adresse
          type: email
          position: right
          validate:
            required: true

        - name: message
          label: Message
          placeholder: Inhalt der Flaschenpost
          type: textarea
          classes: form-control
          position: right
          validate:
            required: true

    buttons:
        - type: submit
          classes: "btn btn-primary btn-lg submit-btn"
          value: Ab ins Wasser
        
    process:
        - email:
            subject: "[Site Contact Form] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
        - message: Und weg ist sie.
---

**Comment by flaviocopes** [comment]
Thanks, I tested and I got the email. Try testing with mailtrap.io https://github.com/getgrav/grav-plugin-email#testing-emails to make sure it's not an issue with the email plugin configuration

**Comment by flaviocopes** [comment]
Closing as it's not a form issue
