### ISSUE TITLE
empty _json object on onFormProcessed event

### ISSUE THREAD

**Issue by gbelvedere** [getgrav/grav-plugin-form#147]
With a  form with a field named "image" to received an upload, I just get an empty _json field with an empty "image" property (the name of my field in the form) instead of the filenames.

**Comment by flaviocopes** [comment]
Thanks for reporting, just fixed - a 2.6.0 Form plugin release should be available shortly.

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-plugin-form/commit/47718f9be8f711987e1595d9b0c15399c139b502
