### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by Neiromaster** [getgrav/grav-plugin-form#149]
For a day, I'm trying to add forms to my pages, but the `process` block is ignored during processing. This happens in the Comments plug-in and Login. Tried on three servers and two PCs. Tell me, what am I doing wrong? Or there are not enough modules for PHP?

**Comment by bobrocke** [comment]
Post some code for others to review?

**Comment by Neiromaster** [comment]
[grav-plugin-login profile.md](https://github.com/getgrav/grav-plugin-login/blob/develop/pages/profile.md)
[grav-plugin-login register.md](https://github.com/getgrav/grav-plugin-login/blob/develop/pages/register.md)
and
[grav-plugin-comments comments.yaml](https://github.com/getgrav/grav-plugin-comments/blob/develop/comments.yaml)
In all these files there is a section Process, which simply does **not work** for me.
In login.php -
```php
public static function getSubscribedEvents()
    {
        return [
            'onPluginsInitialized' => [['initializeSession', 10000], ['initializeLogin', 1000]],
            'onTask.login.login'   => ['loginController', 0],
            'onTask.login.forgot'  => ['loginController', 0],
            'onTask.login.logout'  => ['loginController', 0],
            'onTask.login.reset'   => ['loginController', 0],
            'onPagesInitialized'   => ['storeReferrerPage', 0],
            'onPageInitialized'    => ['authorizePage', 0],
            'onPageFallBackUrl'    => ['authorizeFallBackUrl', 0],
            'onTwigTemplatePaths'  => ['onTwigTemplatePaths', 0],
            'onTwigSiteVariables'  => ['onTwigSiteVariables', -100000],
            'onFormProcessed'      => ['onFormProcessed', 0]
        ];
    }
// and
public function onFormProcessed(Event $event)
    {
        $form = $event['form'];
        $action = $event['action'];

        switch ($action) {
            case 'register_user':
                $this->processUserRegistration($form, $event);
                break;
            case 'update_user':
                $this->processUserProfile($form, $event);
                break;
        }
    }
```
The `getSubscribedEvents()` function _works_, but when I click the Submit button on forms, the page only **reboots**. The function `onFormProcessed(Event $ event)` does _not work_ at all.

In the Admin plug-in everything **works**:
```yaml
process:
    register_admin_user: true
```
But the buttons are created in a twig file:
```twig
        <div class="form-actions primary-accent">
            <button type="reset" class="button secondary"><i class="fa fa-exclamation-circle"></i> {{ 'PLUGIN_ADMIN.LOGIN_BTN_CLEAR'|tu }}</button>
            <button type="submit" class="button primary"><i class="fa fa-sign-in"></i> {{ 'PLUGIN_ADMIN.LOGIN_BTN_CREATE_USER'|tu }}</button>
        </div>
```

**Comment by bobrocke** [comment]
Do you have Xdebug set up? If you put a breakpoint at the start of `onFormProcessed(Event $event)`, is it called? Does one of the switch cases match?

**Comment by Neiromaster** [comment]
I have not XDebug. But I added the incorrect code in onFormProcessed (Event $ event). He did not fulfill. The code was added to the very beginning of the method.

**Comment by bobrocke** [comment]
So the processing script is not being called. What does the form's configuration file look like?

**Comment by Neiromaster** [comment]
I'm trying to use this plugin.
[login](https://github.com/getgrav/grav-plugin-login)
I do not make any changes. I want to display the registration form. The form appears, but when the confirmation button is clicked, the page is updated without errors and warnings. A new user is not created at the same time.
The configuration files in your plugin and in Login did not change. Just added a link to the registration page.
I use Russian localization. But when I changed to default, the problem did not disappear.
In system.yaml all events are enabled

**Comment by flaviocopes** [comment]
@Neiromaster if you already tried changing the web server, it could simply be the form you're using is not correctly indented. Indentation of the form definition matters, try checking that.

**Comment by Neiromaster** [comment]
I made a fresh site using Rtfm skeleton
[http://vegancoder.r35590.hostde11.fornex.org/](http://vegancoder.r35590.hostde11.fornex.org/)
In the Basics section, I added comments for each page.
Here - [http://vegancoder.r35590.hostde11.fornex.org/register](http://vegancoder.r35590.hostde11.fornex.org/register) I added register form.
I did not make any changes to the code. Only for comments added a line from the documentation for the Comments plug-in.
On the page [http://vegancoder.r35590.hostde11.fornex.org/admin](http://vegancoder.r35590.hostde11.fornex.org/admin) you can go under the credentials admin: ASDqwe123
I'm already tired of fighting this problem ...
Server is deployed to Apache

**Comment by flaviocopes** [comment]
PM me your user/ folder in Slack, I need to check it locally

**Comment by flaviocopes** [comment]
After debugging the user/ folder, the problem happens when there is no page that defines a form. On it.

**Comment by rhukster** [comment]
Guys can you test with my PR: https://github.com/getgrav/grav-plugin-form/pull/152

**Comment by Neiromaster** [comment]
Registration is fixed, but comments continue to not work

**Comment by flaviocopes** [comment]
@Neiromaster I pushed a fix for Comments yesterday, can you test the latest develop release? Not yet released in the GPM, but here: https://github.com/getgrav/grav-plugin-comments/archive/develop.zip

**Comment by Neiromaster** [comment]
Everything is working!
