### ISSUE TITLE
Form data being double escaped

### ISSUE THREAD

**Issue by timdmackey** [getgrav/grav-plugin-form#155]
My form data is being double escaped, and I can't figure out why. The second round of escaping is happening in the default `data.html.twig` file, but I can't figure out where the initial escaping is happening. I'm running PHP 5.5.36, so magic quotes shouldn't be an issue. I'm not sure if this is related, but I also have twig autoescaping turned off.

Using this test input:
```
“ ” ‘ ’ ' " ` ~ ! @ # $ % ^ & * ( ) - _ = + [ { } ] \ | ; : , < > . / ? 
```

This is the escaped html output one would expect:
```
“ ” ‘ ’ &#039; &quot; ` ~ ! @ # $ % ^ &amp; * ( ) - _ = + [ { } ] \ | ; : , &lt; &gt; . / ?
```

This is the actual output with the default `data.html.twig` file:
```
“ ” ‘ ’ &amp;#039; &amp;quot; ` ~ ! @ # $ % ^ &amp;amp; * ( ) - _ = + [ { } ] \ | ; : , &amp;lt; &amp;gt; . / ?
```

Removing the `|e` escape filter in `data.html.twig` fixes the double escaping, but where is the second round of escaping coming from? I even tested this with a bare installation of the Landio skeleton, and I'm getting the same results, both on my test server and my production server (which is a shared host subscription). Interestingly, the [Landio skeleton demo](https://demo.getgrav.org/landio-skeleton/) doesn't have this issue, so I have to think it's a problem with my configuration, but I'm at a loss as to what the problem might be.

**Comment by rhukster** [comment]
What theme are you using?

**Comment by timdmackey** [comment]
Landio for both my site and for the skeleton that I tested. My own landio theme is heavily modified, but not in a way that would affect this issue. I updated both installations so that the core and plugins were up to date.

**Comment by rhukster** [comment]
i just installed on my local (mac with brew-based apache/php) and got:

```
Thank you for your feedback!
Your email was sent. Thank you !

Name: test
Email: test@mac.com
Message: “ ” ‘ ’ &#039; &quot; ` ~ ! @ # $ % ^ &amp; * ( ) - _ = + [ { } ] \ | ; : , &lt; &gt; . / ?
```

So yes, i think it must be something with your PHP.  It does 'sound' like magic quotes is enabled.  Have you checked php.ini?  what about a:

```
<?php phpinfo():
```

?

**Comment by timdmackey** [comment]
`'--enable-magic-quotes'` it's listed under the "configure command", but nowhere else. According to the PHP docs, though, the [feature was removed in v5.4.0](http://php.net/manual/en/security.magicquotes.php), so even with the configure command there I'm not sure how it could be in my installation?

**Comment by timdmackey** [comment]
Wait, is your code snippet what printed to the page? Or is it the raw html code? Because what's printed to the page should be the original characters, not the escaped ones like you have. If they're escaped on the page, it means they're double escaped in the code.

**Comment by timdmackey** [comment]
BTW, by default, the confirmation page uses the same twig template as the html email does.

**Comment by rhukster** [comment]
Actually that's the output, but the log file doesn't have any escaping at all:

```
name: test
email: test@test.com
message: “ ” ‘ ’ ' " ` ~ ! @ # $ % ^ & * ( ) - _ = + [ { } ] \ | ; : , < > . / ? 
```

**Comment by timdmackey** [comment]
The log file uses a different twig template (`data.txt.twig`) that doesn't use the escape filter, so my log files don't have any escaping either. That's even more confusing to me, because I would have expected to see one round of escaping there.

This is the print line for a field in `data.txt.twig`:

```twig
{%- set value = form.value(field.name ?? index) %}
{{- field.name ?? index }}: {{ string((value is iterable ? value|json_encode : value)) ~ "\r\n" }}
```

and this is the print line for a field in `data.html.twig`:

```twig
<strong>{{ field.label|t|e }}</strong>:
[snip]
{{ string(form.value(field.name)|e)|nl2br }}
```

**Comment by flaviocopes** [comment]
Oh I see, having both `string()` and `|e` in https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/default/data.html.twig#L24 is causing the issue.

I see @rhukster removed the escape line in https://github.com/getgrav/grav-plugin-form/commit/4052bc78160a7996eb5ffe6769e31c9923da52c8 but I re-added it in https://github.com/getgrav/grav-plugin-form/commit/afa6eab9f5e86cff7300f793227c8422a745e6d1.

@timdmackey this commit should fix the problem: https://github.com/getgrav/grav-plugin-form/commit/0db68c335abdff01d50a205c067196d82e0f8a34

**Comment by timdmackey** [comment]
Commit https://github.com/getgrav/grav-plugin-form/commit/0db68c335abdff01d50a205c067196d82e0f8a34 correctly fixes the issue. I also tested the escaping on names and values for radio, checkbox, selectbox, and textarea, and none of them were affected by this issue. We should be good to go!

By the way, what is the string() function in `{{ string(form.value(field.name))|nl2br }}`? I can't find any documentation on it. Initially when I was trying to diagnose this problem, I glossed over that because I had no idea what it was.

**Comment by flaviocopes** [comment]
`string()`

> Returns a string from a value. If the value is array, return it json encoded

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Twig/TwigExtension.php#L820-L834

(documented just now)

**Comment by mahagr** [comment]
@flaviocopes Escaping needs always to be the last action, otherwise auto-escaping won't work correctly. I would add `|raw` filter into everywhere you do not want to escape -- I'm planning to force the auto-escaping on in 2.0 branch because of I've seen way too many potential XSS issues in the plugins and themes.
