### ISSUE TITLE
HTML tags added via append and prepend attributes closes themselves

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav-plugin-form#159]
Hi, 

It looks like adding html via the prepend or append attribute makes the added tags close themselves:
Exemple:
![capture](https://user-images.githubusercontent.com/12809352/27321542-de3d4b24-559a-11e7-877a-c0486568c692.PNG)

As you can see on this screenshot, I only added two opening tag `<ul>` and `<li>` but it outputs to 
```
<ul><li></li></ul>
```

**Comment by flaviocopes** [comment]
Hi Paul, I think it's the browser automatically closing them, as they are inside a `<div>` tag. You can check by using "View source" (which prints the bare-bones HTML outputted by Grav) instead of the browser inspector (which is the HTML interpreted by the browser). Can you confirm?

**Comment by paulmassen** [comment]
Damn, you are right, developer tools displays the tags as closed. What a curious behavior.

On a second note, don't you think the prepended and appended elements could wrap the entire field, and not only the input itself. I think in most cases, users could want these fields to be inside bootstrap colums or, like in my case, an unordered list. 

Let me know if we should discuss this in an other issue.

Thanks again for your help

**Comment by flaviocopes** [comment]
In this case the best option would be to override the default form.html.twig file, and provide your own markup.

**Comment by flaviocopes** [comment]
(closing)
