### ISSUE TITLE
Validate radio button seems to be killing field value

### ISSUE THREAD

**Issue by bobbwal** [getgrav/grav-plugin-form#160]
Without validate all seems to be working but when I add the validate setting my field values disappear.
~~~~ 
type: radio
options:
  yes: Yes
  no: No
validate:
  required: true
~~~~ 

Gives:
`<input type="radio" value required="required">`
Note the blank value. I'm using fieldsets, not sure if that is relevant. I also have some other stuff going on so will strip it back and see what happens. 

Any ideas? Thanks

**Comment by bobbwal** [comment]
Hmm, I don't think this is specific to radio buttons, more likely I'm misunderstanding how the validation works. I'm trying to integrate this for my radio buttons https://codepen.io/renvrant/pen/ogeeBY

**Comment by flaviocopes** [comment]
This is what I get with your code on Antimatter:

![screen shot 2017-06-29 at 18 01 55](https://user-images.githubusercontent.com/11783388/27697633-2236a648-5cf5-11e7-8894-e1d59aed24a2.png)

the theme might influence the fields rendering, so first try on Antimatter if you still got the issue.

**Comment by bobbwal** [comment]
Thanks for the reply, I really need to make a habit of checking against antimatter. All working now, some of my js was causing funny business.
