### ISSUE TITLE
Optgroup support in Select list 

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-form#165]
Does form support the optgroup tag in a select list?
Seen here: https://www.w3schools.com/TAGs/tag_optgroup.asp

**Comment by flaviocopes** [comment]
No, not yet

**Comment by jgonyea** [comment]
Is anything else needed for this? Can it be closed?

**Comment by w00fz** [comment]
Thanks @jgonyea  this is all good now and can be closed
