### ISSUE TITLE
Validation error message uses field name rather label

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav-plugin-form#17]
When a `required` validation fails, the error message references the field name. If the field name and label are different, then the web user has no idea which field the message relates to as he doesn't see the field name only the label. Wouldn't it make more sense to use the field label instead to reference the non-validating field in the error message?

Example:
```
    - name: platform
      label: OS & Language
```
and the message:
`Validation failed: Missing required field: platform `

**Comment by rhukster** [comment]
Should be fixed with latest Grav develop version
