### ISSUE TITLE
Form notices unreliable

### ISSUE THREAD

**Issue by sunyatasattva** [getgrav/grav-plugin-form#171]
I'm having a problem whereby the form confirmation messages gets shown unreliably. The email gets sent and received correctly, but the confirmation notice mostly doesn't show up in my production environment (and mostly does show up in my local dev environment). Sometimes the notice gets stuck no matter what and shows up even if I open an incognito window with the page.

How can I debug this issue?

---

As requested by @flaviocopes, cross posting this from https://github.com/getgrav/grav-plugin-email/issues/57

**Comment by rhukster** [comment]
Do you have `never_cache_twig: true` set in your page header? That might resolve issues where things are not getting cleared out in sync with cache and session.

**Comment by mahagr** [comment]
Closed due to inactivity -- cannot be reproduced.
