### ISSUE TITLE
Where is 2.8.2 release?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-form#177]
2.8.2 released [4 days ago](https://github.com/getgrav/grav-plugin-form/releases).
Not showing up in admin. Still on 2.8.1 on [getgrav downloads](https://getgrav.org/downloads/plugins).

**Comment by rhukster** [comment]
Ugg.. a plugin repo rename was breaking GPM regen again.  We really need to get that sorted! All fixed now.
