### ISSUE TITLE
Tabbed form layout support

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-plugin-form#178]
I've noticed blueprint forms for the admin plugin support splitting the form into tabs. This is not available to end user forms. Has this never been attempted, or was it considered too difficult, or unnecessary? Just wondering why. Have asked in Slack already.

I plan to build this if nobody warns me against it. I'll share, of course. I've been trying to think of YAML markup patterns that won't break existing forms and templates.

Will appreciate any knowledgeable voices of encouragement/discouragement in this quest.

**Comment by rhukster** [comment]
it should be a matter of porting the `tab` and `tabs` fields from admin to the regular form plugin.  The problem is that the theme has to support some kind of tab handing for it to render correctly.  The form plugin 'could' provide it's own, but on the frontend, this is something that you usually want styled.

**Comment by hughbris** [comment]
OK so it sounds like it was just never ported, or maybe because of the styling issue you mention.

To reduce confusion and prevent inconsistency with admin's tabs, it might be better to couch this feature in terms of form sections. (These shouldn't be confused with fieldsets either!) That way, there's also no expectation for templates to support rendering as tabs.

Just thought of that approach, it needs further consideration.

I do think the plugin could use some devices to improve the aesthetics/UX of long forms. Columns were a positive step.

BTW .. 

>  The problem is that the theme has to support some kind of tab handing for it to render correctly.

doesn't that also apply to the columns feature?

**Comment by rhukster** [comment]
columns are simply a single line of CSS, tabs need to have a style that matches the theme in which they are used.  A simple tab style could be provided an overridden i suppose.

**Comment by hughbris** [comment]
> columns are simply a single line of CSS

Can you provide this CSS one-liner BTW? I asked in Slack earlier and got no response. Had a hack with limited success but CSS is not my thing.

**Comment by hughbris** [comment]
I decided to split my form using accordions instead of tabs but it's a similar requirement.

I used fieldsets to successfully achieve this, but form "sections" do not strictly equate to fieldsets and it required a pretty hacky template override.

Thinking about this a little since I posted the issue, I think it would be handy to have "agnostic" generic field groupings distinct from fieldsets (because that term has semantics and set markup in standards). It should be a pretty easy addition piggybacking off the work of the `fieldset` and `col` field types (recursive templates etc).

Then I won't need to use the "hack" of fieldsets to get groupings within a form and would even be able to have fieldsets within my groupings. It would suit rendering as tabs, accordions or possibly other UI widgets/patterns.

Would you be open to that kind of inclusion? (I know, scope in this plugin is kind of blowing out, right?)

**Comment by mahagr** [comment]
Tabs have been implemented in Form 3.0.
