### ISSUE TITLE
Mail Sending twice

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav-plugin-form#184]
While submitting form, email send to one email id .but  refreshing the same page again and again the same  mail repeatedly forwarding to that email id .Can you suggest a solution for this issue ?

**Comment by rhukster** [comment]
You should put a `reset: true` in the actions of your form.  This way the form is cleared and reset after a successful submission.

**Comment by geogeorgejoseph** [comment]
After adding reset: true form fields resets,but refreshing the page the mail again send to same mail id

**Comment by rhukster** [comment]
Can you paste a copy of your markdown page of your form definition? Please use a code block or s gist to maintain spacing

**Comment by geogeorgejoseph** [comment]
title: 'Enquire form'
published: true
cache_enable: false
visible: true
form:
    name: contact-form
    id: enquiry-form
    action: ''
    fields:
        -
            name: name
            label: Name
            autofocus: 'on'
            autocomplete: 'on'
            type: text
            validate:
                required: true
                message: 'Please enter the name'
        -
            name: email
            label: Email
            type: email
            validate:
                required: true
        -
            name: phone
            label: Phone
            type: text
            validate:
                required: true
                pattern: '\(?\d+\)?[-.\s]?\d+[-.\s]?\d+'
        -
            name: company
            label: Company
            type: text
            validate:
                required: false
        -
            name: g-recaptcha-response
            label: Captcha
            type: captcha
            outerclasses: captcha-field
            recaptcha_site_key: ''
            recaptcha_not_validated: 'Captcha not valid!'
            validate:
                required: true
    buttons:
        -
            type: submit
            value: INQUIRE
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}', '{{ form.value.email }}']
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you for your feedback!'
        -
            reset: true

**Comment by geogeorgejoseph** [comment]
`---
title: 'Enquire form'
published: true
cache_enable: false
visible: true
form:
    name: contact-form
    id: enquiry-form
    action: ''
    fields:
        -
            name: name
            label: Name
            autofocus: 'on'
            autocomplete: 'on'
            type: text
            validate:
                required: true
                message: 'Please enter the name'
        -
            name: email
            label: Email
            type: email
            validate:
                required: true
        -
            name: phone
            label: Phone
            type: text
            validate:
                required: true
                pattern: '\(?\d+\)?[-.\s]?\d+[-.\s]?\d+'
        -
            name: company
            label: Company
            type: text
            validate:
                required: false
        -
            name: g-recaptcha-response
            label: Captcha
            type: captcha
            outerclasses: captcha-field
            recaptcha_site_key: 6LcH0ioUAAAAAJrFCYC5lNmhnoXsOMdANqzjmqJ3
            recaptcha_not_validated: 'Captcha not valid!'
            validate:
                required: true
    buttons:
        -
            type: submit
            value: INQUIRE
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}', '{{ form.value.email }}']
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you for your feedback!'
        -
            reset: true
---
`

**Comment by rhukster** [comment]
Ok fixed this in develop branch
