### ISSUE TITLE
Changing form.twig.html doesn't change anything

### ISSUE THREAD

**Issue by ekiwnox** [getgrav/grav-plugin-form#185]
Hi guys,

I'm writing here because I had a weird issue recently. 
I did a page composed of module in a modular page. In this page, I tried to create a module with two columns : one for a text and the second one for a form. 

So naturally, I tried to change the form.twig.html that's in my templates folder (Theme/templates/form). I've seen that I cannot change anything, or I can but anything is changed on the frontend which is very annoying because I can't do any modification of the template. I also tried to delete this template and nothing appends. The form was working perfectly but I couldn't achieve the modification I wanted. I simply wanted to wrap the form in a div and wrap the text + the div with the form in a new div, but couldn't do that.

I also tried to change the code of the plugin itself. So I succeed by adding a div around all the code of the form.twig.html (The one in the plugin folder in the default folder). At the end of all this process, I couldn't achieve what I wanted, because I cannot wrap my text and my form in a single div, which is so sad...

I tried to find some help directly on the Slack of Grav and some guys tried to help me (thanks), but they couldn't find how to change the form template...

Would be nice to have the ability to just put an {%include form%} to include a whole form in a module or to be able to change that crappy form.twig.html that's seems useless for the moment... :-) 

EDIT : Would be also nice to have a nice documentation about how the form work, because at the moment, the Grav documentation is not enough to understand how the plugin work :-) 

Thank you so much ! Have a nice day!

**Comment by rhukster** [comment]
If you override the `form.html.twig` in your template, then it should definitely use that.  However, if you look at this file in the form plugin, its really just including `forms/form.html.twig` and this is in turn just including `forms/default/form.html.twig`, so this last file is really where the meat of the form output is coming from.
