### ISSUE TITLE
New support of an input tag's size attribute conflicts with use of size as styling class for wrapper div

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav-plugin-form#19]
I know I proposed the size attribute myself, but now while working with forms realized that the introduction of the size attribute for the input field with commit hwmaier@28b0ace is clashing with using size as a general css style class in the form field's div wrapper `<div class="form-input-wrapper {{ field.size }}">. At present if somebody sets size to large, the large also would be passed to the input tag which generates invalid html. See field.html.twig.

Maybe we should remove it again or can this be resolved somehow? Any suggestions?

**Comment by rhukster** [comment]
I'm ok with leaving this.  Generally speaking you use one or the other.  If you use manual approach you are not going to be creating CSS for the class approach, and vice versa.

**Comment by hwmaier** [comment]
You are not concerned having some invalid values in the size attribute like this?
```
<input size="large" ....>
```

**Comment by rhukster** [comment]
Oh i didn't know that it would share the size attribute, thought it was going to keep the class attribute.  I guess we either need to fix this to ensure the correct attributes are used for each (not combined) or revert.

**Comment by flaviocopes** [comment]
We can rename that to `sizing` perhaps, so both can be used

**Comment by flaviocopes** [comment]
After reading this btw https://stackoverflow.com/questions/1480588/input-size-vs-width/1480592#1480592 I'm not sure "size" is better over just using CSS

**Comment by hwmaier** [comment]
Yeah, maybe size is a bit old fashioned indeed and has little use nowadays. They still carried it over to HTML5 though. OK let's get rid of it, was a bad idea, sorry for the confusion.

**Comment by hwmaier** [comment]
Or one could test if its a number then its meant to be an attribute of input otherwise its a style of the surrounding div.

**Comment by flaviocopes** [comment]
I think that is a bit too much "magic" logic for a form attribute, if the `size`is just a presentation attribute, then CSS is the way to go

**Comment by hwmaier** [comment]
Good. And there is always the option to create a custom template to suit such special requirements.
