### ISSUE TITLE
wrong quote sign

### ISSUE THREAD

**Issue by roootliner** [getgrav/grav-plugin-form#191]
https://github.com/getgrav/grav-plugin-form/blob/54b1470d03169d962c468d75c0115f0b2181fcb1/languages.yaml#L289

is:
    FILEUPLOAD_PREVENT_SELF: 'Nie można użyć "%s" poza stronami.’
should:
    FILEUPLOAD_PREVENT_SELF: 'Nie można użyć "%s" poza stronami.'

**Comment by rhukster** [comment]
Fixed in develop
