### ISSUE TITLE
Newly introduced defaulting of field type to text does not work

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav-plugin-form#20]
The feature I introduced in https://github.com/getgrav/grav-plugin-form/commit/50a6eb3583ad96648495665b18b0a09d42865c3d does not really work once forms are submitted. I realised that the support of defaulting the type to text cannot be handled at template level alone. Support must be added to the form plugin's post method and the core's Blueprint class.

So I suggest to either withdraw the feature or add it to those two PHP files (and then it can be removed from the templates/forms/default/form.html.twig file).

I am happy to create a PR for either option, please advise.

**Comment by flaviocopes** [comment]
I think we can drop that and explicitly set the field types as before, what you think?

**Comment by hwmaier** [comment]
Let's revert that too to get it off the issue list.

**Comment by flaviocopes** [comment]
Done in https://github.com/getgrav/grav-plugin-form/commit/b2c80d41e8bf3199606b9ce257aa33c5c8d43ae0
