### ISSUE TITLE
Bring back filesize option for file field

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav-plugin-form#202]
I noticed that the filesize option had been removed from the file field in version 2.9.3 (6f7b2e632c7b11cf8c79c16271e3df79a3369934).

I couldn't find an issue that preceded the removal – I was just wondering why it was removed? If a site has public facing forms with file uploads, it's not given that you would want to use the global filesize limit (for example, you might want to be able to upload larger files through the admin panel).

**Comment by rhukster** [comment]
I was already thinking about how to do this 'better' so have just pushed a solution where this is added back but defaults back to system PHP limits if value is `0` or larger than PHP value.  Please test it out and let me know if this is working as expected (works in my testing).
