### ISSUE TITLE
Confusing use of template in form

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-form#212]
For now, it's impossible to target `form-message.json.twig` as template.

Apparently it's because this param don't like extension.

In the form frontmatter, the field `template` can only contain the name without extension and by default it return the html version of the target template.

That's mean it's impossible to target `form-message.json.twig`

For an AJAX contact form, the only solution I found is to add '.json' at the end of the path in the JS.

I found this behaviour very confusing and it tooks me a lot of time to understand.

It should be so much better if we could define the template version (html or json) from the frontmatter!

Thank you

**Comment by jimblue** [comment]
Just for people trying to use json this is the JS hack for now.

```
  var form = $('#contact')

  // FORM SUBMISSION
  form.on('submit', function (event) {
    // PREVENT DEFAULT FORM SUBMISSION
    event.preventDefault()

    // SUBMIT THE FORM VIA AJAX
    $.ajax({
      type: form.attr('method'),
      url: form.attr('action') + '.json',
      data: form.serialize(),
      dataType: 'json',

      // AJAX REQUEST => TRANSFER COMPLETE
      success: (gravResponse, ajaxStatus, xhr) => {
        var httpCode = xhr.status

        // RESPONSE HTTP CODE => SUCCES
        if (httpCode >= 200 && httpCode < 400) {
          // THE STATUS RETURNED IN GRAV RESPONSE (succes or error)
          let gravResponseStatus = gravResponse.status

          // THE MESSAGE RETURNED IN GRAV RESPONSE (idealy just the message without html)
          let gravResponseMessage = gravResponse.message

          // IF GRAV FORM RESPONSE STATUS IS SUCCES
          if (gravResponseStatus === 'success') {
            // GRAV success callback
          }

          // CHECK GRAV FORM RESPONSE STATUS
          if (gravResponseStatus === 'error') {
            // GRAV error callback
          }
        // RESPONSE HTTP CODE => ERROR
        } else {
         // HTTP code error callback
        }
      },

      // AJAX REQUEST => TRANSFER FAILED
      error: (xhr, ajaxStatus, errorThrown) => {
        // AJAX code error callback
      }
    })
  })
```

**Comment by rhukster** [comment]
This is a page feature and is documented: https://learn.getgrav.org/content/headers#template (always been this way)

**Comment by jimblue** [comment]
Hi @rhukster, thanks to point this out, I didn't knew this feature.
But I just try and it didn't resolve the problem in my case:

<img width="222" alt="screen shot 2017-12-05 at 05 28 45" src="https://user-images.githubusercontent.com/10623367/33590157-df31e15e-d97d-11e7-8198-36cc8d22caae.png">

As you can see the form is in a modular, is it the reason?

**Comment by jimblue** [comment]
Hi @rhukster,

Can you please re open this issue?

Using `template_format` style doesn't work in modular...

**Comment by jimblue** [comment]
@rhukster have you been able to replicate this problem?

**Comment by jimblue** [comment]
Now that we now where is the problem I'm closing this issue to open a new one with more appropriate title and description.

Cheers
