### ISSUE TITLE
Two column form layout

### ISSUE THREAD

**Issue by kpranke** [getgrav/grav-plugin-form#214]
Is it possible atm to create a two column form layout? For example, I'd like to have two input fields in the left column and one bigger textarea on the right side.

**Comment by jpcbarros** [comment]
Yep, the ability to create complex form layouts would be very good. For instance, I am trying to create a two column layout with one the rows having 3 fields (1 on the first column and 2 on the other), and it isn't possible.

**Comment by rhukster** [comment]
You can use `columns` and `column` nested fields to do this, or CSS columns, or even CSS flexbox if you add some classes.  I prefer CSS columns as it doesn't require any extra HTML markup
