### ISSUE TITLE
Base form notices css classes

### ISSUE THREAD

**Issue by jwillp** [getgrav/grav-plugin-form#215]
I noticed that the plugin uses the same kind of CSS classes as the markdown-notices plugin for its alerts/notices colors:

```html
<div class="alert notices {{ form.message_color ?: 'green' }}"></div>
<div class="alert notices yellow"></div>
``` 

The markdown-notices plugin has a configuration parameter that allows to change these color classes.
However the form plugins does not as I see in the code (except for manually specifying a message_color attribute on a per form basis, or overriding the twig form template).

It would be great if the form plugin could check for the values of the markdown-notices if it is installed and use these in place of the default green,yellow,red,blue hardcoded values.

**Comment by rhukster** [comment]
We're actually moving away from this and setting some standard classes like `error`, `success` etc.  If you want to modify this you can always override the `partials/messages.html.twig` file that has been moved to the Grav core: https://github.com/getgrav/grav/blob/develop/system/templates/partials/messages.html.twig
