### ISSUE TITLE
Issue as requested: vundefined

### ISSUE THREAD

**Issue by RobLui** [getgrav/grav-plugin-form#222]
'Think there’s a typo @... screenshot provided (just pulled the 1.4 repo) name: “vundefined”
<img width="1179" alt="vundefined" src="https://user-images.githubusercontent.com/10846766/34134086-c8bf3058-e458-11e7-9f33-e07f7637dc62.png">

**Comment by rhukster** [comment]
Fixed in latest 1.4 branch of Grav.
