### ISSUE TITLE
Mail content with disabled label

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#223]
With [this PR](https://github.com/getgrav/grav-plugin-form/pull/126) I can use such line in my field definition:
```
label: false
```

But in test mail I see this:
![image](https://user-images.githubusercontent.com/7556290/34187902-b808f0b8-e544-11e7-870e-cb85c98a551d.png)

No label in field = no label in mail.

How to turn off label but leave in the mail?

**Comment by rhukster** [comment]
This is resolved by setting the label back again, but using:

```
display_label: false
```

https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/default/field.html.twig#L18
