### ISSUE TITLE
Autocomplete: off works only with apostrophes

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#224]
If we have this line in field definition:
```
autocomplete: off
```
than autocomplete off isn't working (no attribute).

Disabled only with apostrophes:
```
autocomplete: 'off'
```

Enabling with `on` show `autocomplete="1"`, and with `'on'` show `autocomplete="on"`.

**Comment by rhukster** [comment]
This is a 'feature' of yaml, `off` without quotes is converted to a boolean value.

**Comment by Sogl** [comment]
Closed because it's not bug but feature 😄
