### ISSUE TITLE
form_button_outer_classes

### ISSUE THREAD

**Issue by bambrillo** [getgrav/grav-plugin-form#226]
In general form template file form.html.twig there is a line
`{% block inner_markup_buttons_start %}<div class="{{ form_button_outer_classes ?: 'buttons'}}">{% endblock %}`
Searching in Google, searching in Form plugin files, trying to set button_outer_classes form attribute in markdown brings no effect.

**Comment by dimitrilongo** [comment]
you need to define `form_button_outer_classes` on theme `onTwigInitialized` in `your-theme.php`
