### ISSUE TITLE
Markdown in form label to add page link

### ISSUE THREAD

**Issue by hgiritzer** [getgrav/grav-plugin-form#227]
Hi,

I'd like to use Markdown in a form label to add a site-relative page link as described here:

https://discourse.getgrav.org/t/markdown-in-form-label-to-add-page-link/5386

HTML would work right now, but i.e. for a multi-language site, the easiest option I know of is a Markdown relative link, which automatically adds the /cms/en/ part in front of the relative page url (i.e. /legal/privacy).

Best regards,
HeliG

**Comment by rhukster** [comment]
does this need to be in the label? I ask because i just added markdown support to the `field.description` value (when you have `markdown: true` on the field).

**Comment by hgiritzer** [comment]
I would really appreciate to have it in the label, as this would fit perfectly for my type: checkbox field (link in the same bold formatted line, as recommended by my attorney).

**Comment by rhukster** [comment]
done.
