### ISSUE TITLE
Conflict with the gravstrap plugin

### ISSUE THREAD

**Issue by olympus642** [getgrav/grav-plugin-form#229]
Hi,
It looks like there is a conflict between the form plugin and the gravstrap plugin and/or the shortcode-core plugin.
In the ceevee theme : [https://demo.getgrav.org/ceevee-skeleton/](https://demo.getgrav.org/ceevee-skeleton/) with the gravstrap plugin (v1.2.3) installed, after updating the form plugin (v2.11.1), my contact form does not appear anymore. Maybe the following discussion can help us? : [https://discourse.getgrav.org/t/shortcode-core-plugin-seems-uncompatible-with-form-plugin/1785](https://discourse.getgrav.org/t/shortcode-core-plugin-seems-uncompatible-with-form-plugin/1785)
Thank you in advance !

**Comment by axel-rank** [comment]
i had a similar issue after form update:
https://github.com/getgrav/grav-plugin-form/issues/217
Try to move your form definition from modular.md to  _contact/form.md header.

**Comment by olympus642** [comment]
It works ! Vielen Dank :)
