### ISSUE TITLE
Form and Captcha - Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by xetorixik** [getgrav/grav-plugin-form#238]
Using the form (test as end-user)  and the Google reCAPTCHA function the following error appear in the console of Chrome, Opera, Firefox. 
Thereafter the form has been sent, the email just arrives. 
After sending the error disappears.

> Uncaught ReferenceError: $ is not defined 

In code:
> $('form').submit(function(event) {

File: captcha.html.twig
Both the browsers, form plugin and Grav are up-to-date.

Nothing changed to the source code.
Created an form.md and thats it.

Because I get the same error on a test site, other server, other domain I suspect that this can be a bug.
Is this a bug or my mistake? 

Thanks.

**Comment by rhukster** [comment]
You have some other JS error on your page.. Probably not related to captcha.

**Comment by xetorixik** [comment]
Are you sure?
The error only applies on the contact page.
Disabling the recaptcha feature fom the same contact form and the error is gone.

**Comment by xetorixik** [comment]
Have it tested again. 
New domain, new provider, new site with just only grav-skeleton-helium-site-5.4.23.zip and a recaptcha form. Result the same error on only the form page. Disabling recaptcha. 
Error gone.

**Comment by mhilland** [comment]
I had the same issue after upgrading to v2.13.0. It seems the new version adds some jQuery code to the `content` block of your website if you have a form in there, and jQuery doesn't get added to the page until the `javascripts` block after the footer, so its not available, hence the "$ is not defined" error. I fixed this by removing the jQuery line from the `javascripts` block and moving it into the bottom of my `head` block like so:

```
{% block jquery %}
    {% do assets.add('jquery', {'priority': 101, 'group': 'jquery'}) %}
{% endblock %}
{{ assets.js('jquery') }}
```

It should be documented that the plugin now requires jQuery to be loaded in the header!

**Comment by xetorixik** [comment]
@mhilland Thanks Max.
Think you are right.
I have looked at [various themes](https://getgrav.org/downloads/themes) and all/most of them are calling JavaScript's including jQuery after the footer section. Including Grav's team own Helium Theme.

Using your fix resolves the problem immediately.
So only a reference in the documentation does not seem to me to be a structural solution.
Given the fact that most theme's are using scripts in the footer, it should be easier to fix 1 plugin, 
than multiple themes.  

@rhukster what is wisdom? plugin fix, patch all themes as end-user? Leave it alone.

**Comment by rhukster** [comment]
it's kinda tough to fix because every theme has 100% control over how it outputs stuff.  That includes how it handles JS. I typically put my jQuery in the header, and leave other stuff in the footer when things are fully loaded.

Even Quark theme does this:

```
    {% block javascripts %}
        {% do assets.addJs('jquery', 101) %}
        {% do assets.addJs('theme://js/jquery.treemenu.js', {group:'bottom'}) %}
        {% do assets.addJs('theme://js/site.js', {group:'bottom'}) %}
    {% endblock %}
    {{ assets.js() }}
```

Some people insist on putting all JS at the bottom, and I think that often causes problems like this where you have inline JS happening on the page, trying to use things that are not available yet.
