### ISSUE TITLE
update from 2.11.3 to 2.11.5 crashed site

### ISSUE THREAD

**Issue by glasswork** [getgrav/grav-plugin-form#241]
When I updated the Form plugin from 2.11.3 to 2.11.5 it crashed my site with a Crikey!

File involved was form.php 

`class_alias('Grav\Plugin\Form\Form', 'Grav\Plugin\Form');`

Could not find Grav\Plugin\Form\Form

Reverted back to 2.11.3 and site is operational again.

FYI - for some reason this did not crash my local dev site only the remote (AWS EC2) site.

**Comment by rhukster** [comment]
Delete the whole 'user/plugins/form' plugin and reinstall it.  You've 'merged' a new forms plugin on top of the old plugin and it's not replaced everything.

**Comment by glasswork** [comment]
Originally I just clicked update via the Admin and went from 2.11.3 to 2.11.5.

This time I downloaded the zip file from github and installed manually. That went to 2.12.0. 
Same problem, though ... so it is not a partial merge issue.

**Comment by mahagr** [comment]
Which PHP version you're on? The above code shouldn't cause any issues.

**Comment by glasswork** [comment]
According to phpinfo:
PHP Version 7.0.22-0ubuntu0.16.04.1

**Comment by mahagr** [comment]
Additional question: what are your opcache settings?

**Comment by glasswork** [comment]
![screen shot 2018-02-22 at 11 37 28 am](https://user-images.githubusercontent.com/4681577/36557188-cfefe850-17c4-11e8-8b0b-eba98d246d26.png)

**Comment by mahagr** [comment]
One more question: does restarting apache help?

**Comment by glasswork** [comment]
That is a question that will have to wait for an answer.
We have people who need to have the site consistently available and I don't have time to spin up a test site on a server to check that theory because I have other things I need to get done in the next couple of hours.
But I should be able to load the new form plugin back in and restart apache tomorrow though.

Thanks for bearing with me.

**Comment by glasswork** [comment]
No, restarting apache made did not help.

**Comment by RamblingRoss** [comment]
Just to say "me to".

This time running on a shared host (Vidahost) with PHP 7.1.5.

Similar approach taken to try various version of Forms, 2.11.3 being the last working release.

**Comment by mahagr** [comment]
Try uninstalling the plugin and installing it back.

**Comment by glasswork** [comment]
No good.
Also tried updating Login plugin first which updated Form automatically.
Same issue.
Reverted.

**Comment by RamblingRoss** [comment]
As with glasswork I have tried various ways if updating the form plugin - all without luck.

The issue lies somewhere within form.php - I have taken all the other files across from the new form code without issue, but copying across the form.php causes the site to die.

If I get time I will try bringing across the changes within the php file a section at a time to identify the problematic lines.

**Comment by rhukster** [comment]
@glasswork @RamblingRoss - As I posted in that last issue, there's a pretty simple one-time solution:

If you guys physically **delete** the `user/plugins/forms` folder and reinstall it, the form plugin should definitely be fixed.

The underlying issue is that we did change a namespace in `form.php` and that is working for 99% of people with no issues, but for this 1% of people, the server (or the PHP instance) is holding on to some internal compiled version of this file and not picking up the changed reference.  Deleting the form folder and reinstalling it forces the changes to be picked up.  We are not sure how or why this happens, and nothing we have suggested seems to fix it. Only physically deleting it seems to work.  We are still investigating it, but for now you should be able to get back and working.

BTW, this is not something we typically do, but sometimes we just have to clean up things to make them more consistent or to address a potential namespace issue.

**Comment by glasswork** [comment]
I have done so dozens of times.

sent from my phone - forgive typos

**Comment by glasswork** [comment]
I have deleted that folder and reinstalled dozens of times with cache clearing in between. No joy.

**Comment by rhukster** [comment]
I'm not sure how that's possible :(

Could you zip up your site and send me a link?  I could then see if there's anything else that is tripping up the class loader.

**Comment by glasswork** [comment]
I am not at work now so, no. I re-cloned site into a staging area before i left. Basically I am just going to swap out codebase from local where new form plugin is working that way i don't have to worry about what the obstacle is ... will (hopefully) just step over it, as it were.

**Comment by redrohX** [comment]
I had the same issue, but I can confirm deleting the folder `user/plugins/form` and reinstalling the plugin through `./bin/gpm install form` does work for me to get rid of the error.

**Comment by glasswork** [comment]
Zipping is a no-go. Our repo is private and we wish to keep it that way. Sorry.
If you were to specify sections that would be pertinent, I might could do that.

**Comment by glasswork** [comment]
Very glad that it worked for you, @redrohx. I can confirm that it does not work ... for me. 
The moment I pushed to it, it failed again. 
Also, while it seemed to work before pushing and i could view the frontend and get into the backend, I could not actually do anything inside it. For instance, going to admin//plugins/form would fail.

**Comment by glasswork** [comment]
I have used bin/gpm uninstall and install on both local and production.
But even, though I can get into backend I still get the following error (or similar such errors) when trying to actually accomplish anything.

When going here - admin/plugins/archives - I get:
RuntimeException (400)
Unable to find one of the following templates: "forms/fields/select/select.html.twig", "forms/fields/text/text.html.twig" in "partials/blueprints.html.twig" at line 13.

When going here - admin/pages/home - I get:
RuntimeException (400)
Unable to find one of the following templates: "forms/fields/text/text.html.twig", "forms/fields/text/text.html.twig" in "forms/fields/tab/tab.html.twig" at line 6.

So, I always have to revert.

**Comment by glasswork** [comment]
Here is what worked for me - there may be extra non-functional steps in here, but I wanted to document the whole process.

Log out of grav (this was very important).
SSH in to site root.
Do bin gpm uninstall Form and Login (will also do Mail) on Production.
Do bin gpm install Form and Login (will also do Mail) on Production.
(I think the above clears the issue)
Do bin gpm uninstall Form and Login (will also do Mail) on Production (once again - so we can push).

Do bin gpm uninstall Form and Login (will also do Mail) on Local.
Do bin gpm install Form and Login (will also do Mail) on Local.
Push up to git. Pull changes into Production. 
Gave me an incompatible composer error (which threw me).

Decided to do bin gpm install Form and Login (will also do Mail) on Production (again).
Made a small adj to readme file on local and pushed to git. Pulled to Production.

Success.

I failed to do step 1 the first time and could not get back into grav backend even with clearing browser cache and cookies and rebooting server. Kept giving me errors about user not found.

I am not really recommending this solution to anyone - use at your own risk.

**Comment by RamblingRoss** [comment]
@rhukster Many thanks.... using gpm worked - had to jump through a through hoops to gain access to SSH on the hosting account but all is well going that route (as opposed to ftp'ing up the new set of packages)
