### ISSUE TITLE
Custom form markup: Errors not showing and field go blank

### ISSUE THREAD

**Issue by Genenenenaam** [getgrav/grav-plugin-form#243]
Hi,

I have a contact form that requires custom html markup. On submission the data gets saved, but i'm having trouble with field errors.

- The error class isn't rendering on the fields.
- All the fields go blank after submission with field errors.

I'm looking in the original code, but i'm unable to fix this. Could you please help. Thanks.

The custom html markup:
`
{% set method = form.method|upper|default('POST') %}
{% set action = form.action ? base_url ~ form.action : base_url ~ page.route ~ uri.params %}
{% if (action == base_url_relative) %}
    {% set action = base_url_relative ~ '/' ~ page.slug %}
{% endif %}
{% set errors = attribute(form.messages, field.name) %}

    <form name="{{ form.name }}" action="{{ action | trim('/', 'right') }}" method="{{ method }}" class="js-from {{ form_outer_classes }} {{ form.classes }}">

	<fieldset class="
		form__field 
		js-form__field--floating-label 
		field--required
		{% if errors %}field--error{% endif %}
	">
		<label for="data[name]">Name</label>
		<input type="text" name="data[name]" value="" autofocus="autofocus" autocomplete="off" required="required">
		<span class="field__helper-text">Lets make our conversation more personal.</span>
	</fieldset>

	<fieldset 
		class="
			form__field
			js-form__field--floating-label
			field--required
			{% if errors %}field--error{% endif %}
		">
		<label for="data[email]">Email</label>
		<input type="email" name="data[email]" value="" required="required">
		<span class="field__helper-text">We will reply you by email.</span>
	</fieldset>

	<fieldset 
		class="
			form__field
			form__field--select
			field--required
			{% if errors %}field--error{% endif %}
		">
		<label for="data[subject]">Subject</label>
		<select name="data[subject]" id="select" required="required">
			<option value="default">Select a subject</option>
            <option value="research-strategy">Research &amp; strategy</option>
            <option value="ux-ui">UX &amp; UI design</option>
            <option value="project-management">Project management</option>
            <option value="implementation-development">Implementation &amp; Development</option>
            <option value="job-opening">Job opening</option>
            <option value="other">Other</option>
		</select>
		<span class="field__helper-text">What's your question about?</span>
	</fieldset>

	<fieldset 
		class="
			form__field
			js-form__field--floating-label
			field--required
			{% if errors %}field--error{% endif %}
		">
		<label for="data[message]">Message</label>
		<textarea name="data[message]" id="textarea" rows="1" required="required"></textarea>
		<span class="field__helper-text">How can we be of service?</span>
	</fieldset>

	<fieldset 
		class="
			form__field 
			form__field--checkbox
		">
		<label for="checkboxID-1">
			<input name="data[newsletter]" id="checkboxID-1" type="checkbox" value="">
			<span class="field__label--checkbox">Subscribe to newsletter</span>
		</label>
		<span class="field__helper-text">Don't miss out on our latest news updates!</span>
	</fieldset>

	{% include 'partials/form-messages.html.twig' %}

	<fieldset class="form__field">
		<button type="submit" value="Submit">Send</button>
	</fieldset>

	{% include 'forms/fields/uniqueid/uniqueid.html.twig' %}
	{{ nonce_field('form', 'form-nonce')|raw }}

</form>`

Preview of the fields going blank after entering an invalid email 'test@test'
<img width="508" alt="schermafbeelding 2018-03-18 om 23 31 52" src="https://user-images.githubusercontent.com/20650976/37572000-c53011e4-2b04-11e8-9390-fbaebd49dbed.png">

**Comment by rhukster** [comment]
The default form TWIG has support for inline messages if you enable that on the form definition:

https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/default/form.html.twig#L11
