### ISSUE TITLE
Checkbox label does not allow links?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-form#253]
I have a checkbox in my form, the label is: "Agree to the terms and conditions".
In this label I want to put a (page)link to the terms. But as I see it's not possible at the moment?
Do I miss something? Would be great and useful to have this feature.

**Comment by rhukster** [comment]
Actually does, just enable `markdown: true` in the field and use markdown links

https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/fields/checkbox/checkbox.html.twig

**Comment by axel-rank** [comment]
Great, thanks. It's working now.
Docs should be updated. Markdown not listed in common attributes.
https://learn.getgrav.org/forms/forms/fields-available#the-checkbox-field
