### ISSUE TITLE
How to override default templates? [FIGURED OUT]

### ISSUE THREAD

**Issue by heihachi88** [getgrav/grav-plugin-form#254]
"user/plugins/form/templates/default/field.html.twig" for example.

How can i override this template in my custom theme? I've noticed it uses mass includes, one file includes another, etc... Infinite includes 🤣 makes me crazy.

Figured out. Can be closed.

**Comment by saidalkharusi** [comment]
I need help with overriding the default templates as well. I know I can modify the files in user/plugins/form directly but I'm pretty sure those changes will get undone the second a new update comes out. What's a proper way of doing way?

**Comment by heihachi88** [comment]
You can just copy them to you theme and override as you want.

**Comment by saidalkharusi** [comment]
I keep getting `Maximum execution time of 30 seconds exceeded` exception. What files do I copy exactly, and where to? Thanks for your response.

**Comment by rhukster** [comment]
You need to drop them in your theme's `templates/` folder, but you do need to keep the same folder and name as in the form's `templates/` folder.

So if you wanted to override that field.html.twig you would need to copy:

`user/plugins/form/templates/default/field.html.twig` 

to:

`user/themes/yourtheme/templates/default/field.html.twig`

However, I suggest you don't copy the entire thing... Instead, you should copy the wrapper file: `user/plugins/form/templates//field.html.twig` which extends the `default/field.html.twig` and then simply extend the **block** you wish to mess with.

**Comment by saidalkharusi** [comment]
Works beautifully, thanks so much :)
