### ISSUE TITLE
BUG: Custom validation message is not shown on type 'select'

### ISSUE THREAD

**Issue by dannystarkDE** [getgrav/grav-plugin-form#259]
The option validate.message ist not working if the field type is select.

My modular **form.md**:
<pre>
title: Contact
form:
    name: contact
    template: form-messages
    refresh_prevention: true
    fields:
        -
            name: salutation
            label: Anrede
            id: Anrede
            title: Anrede
            classes: 'a-select'
            type: select
            outerclasses: half
            validate:
                required: true
                message: "Anrede wählen."
            options:
                0: Anrede wählen
                mr: Herr
                mrs: Frau
.....
</pre>

Can anyone confirm this?

**Comment by rhukster** [comment]
It's kind of redundant in a select field.  If you want the field to be required, you can just include valid options in the select.
