### ISSUE TITLE
Captcha field requires jQuery 

### ISSUE THREAD

**Issue by andrewvaca** [getgrav/grav-plugin-form#266]
The captcha field in templates/forms/fields/captcha/captcha.html.twig:21 uses jQuery construct without checking jQuery existence. While loading JS libraries at the end of page, it crashes. 

I suggest to wrap the submit event into document.onload event and check for jQuery before using it. Anyone has better solution? Otherwise i will create pull request :)

**Comment by rhukster** [comment]
yes, please create a PR and we can review it.  Cheers.

**Comment by NicoHood** [comment]
@andrewvaca What about the PR?

**Comment by andrewvaca** [comment]
Hi @NicoHood, sorry for my lack of response, I's been rough two years for me (2 kids, covid). Now I'm back on track, but I see someone solve this for me. There is no longer jQuery dependance in the template. I'm closing the issue and as an apology for my incompetence I'll try to solve some other issues in here soon.
