### ISSUE TITLE
How to store current date in a form hidden field

### ISSUE THREAD

**Issue by omojahed** [getgrav/grav-plugin-form#267]
Hello,

I can't save current date in a form hidden field to my data file.

with this code in form.md (no mockery, I'm starting in grav :) ) :

        - name: date
          type: hidden
          default: `r format(Sys.Date(), "%Y-%m-%d")`

or
          default: "`r format(Sys.Date(), "%Y-%m-%d")`"

all other fields are ok in the saved data file (process = save), except the hidden date field, output is :

name: test name
email: email@myemail.com
phone: '0016598784565'
message: "Test message\r\ect ect\r\n"
date: null
ip: 127.0.0.1

Any help ?

**Comment by rhukster** [comment]
You should use `data-default@` and then create a static method in your plugin or theme class that can return the PHP code you are trying to get:

https://learn.getgrav.org/forms/blueprints/advanced-features#using-function-calls-data
