### ISSUE TITLE
Issue with Appi theme form

### ISSUE THREAD

**Issue by starfoxik** [getgrav/grav-plugin-form#277]
I was create site based on Appi theme and form is not working there. It's just redirecting to /home

Here is test form for check the bug fs196.ru/test In some browser like Google chrome its working well but from phone or Edge its just redirecting. No errors in log and no saves in user/data

**Comment by starfoxik** [comment]
Update: the problem is related to caching, I was disabled it and the form worked properly

**Comment by starfoxik** [comment]
Update 2: the problem is still ahead, i was try everything and readed the learn grav doc. I dont undestend why its just redirecting?

**Comment by rhukster** [comment]
It sounds like an issue with Appi, but if you create a form in a modular sub-page you will have caching issues unless you disable caching on the page, or set `never_cache_twig: true` which caches, but always processes the Twig.
