### ISSUE TITLE
Suggest linking label to input for better accessibility to assistive technologies

### ISSUE THREAD

**Issue by fmommeja** [getgrav/grav-plugin-form#279]
Hi,
I suggest to link **label** and **input** fields like this:

```
01.<div class="form-field   ">
02.    <div class="form-label ">
03.        <label for="id-name" class="inline">
04.            Name<span class="required">*</span>
05.        </label>
06.    </div>
07.    <div class="form-data " data-grav-field="text" data-grav-disabled="true" data-grav-default="null">
08.        <div class="form-input-wrapper  ">
09.            <input id="id-name" name="data[name]" value="" type="text" class=" " placeholder="Your&#x20;name" autocomplete="on" required="required" />
10.        </div>
11.    </div>
12.</div>
```

There are just two elements that should be added to the code:

- the first one (on line 09) is an **id** for the _input_ item: ` id="id-name"`

- the second one (on line 03)  is the association of the _label_ item to the _input_ one by adding: ` for="id-name"` to it

so that vocal readers can easily connect these two fields.  :)

More information here: [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/forms/Basic_form_hints](url)

Thank you for your great job!
Kind regards

Fred

**Comment by fmommeja** [comment]
Sorry, didn't see that this functionnality was already implemented.  :)
Just didn't understand how to make it work…

**Comment by johannesE** [comment]
@fmommeja Could you post a link to where you found the solution? Or how you solved it?

**Comment by fmommeja** [comment]
On the **Reference: Form Field Index** documentation page:
[https://learn.getgrav.org/16/forms/forms/fields-available](url) 

you can read that the **id** attribute is available for common fields and also sets the **for** attribute on the **label**.
You just have to include it in your field attributes.  :)
