### ISSUE TITLE
Add Process Type 'Hook'

### ISSUE THREAD

**Issue by sturple** [getgrav/grav-plugin-form#29]
It would be nice to have a Hook Process to the form. 
Not sure of how this would work, Would this have to be in the form of a function in your theme or another plugin
or would it be in the form of a custom function right in the yaml file
or is there somewhere else this could be defined.

Here are some reasons to add a hook
* Be able to a email list registration, (curl call to another site)
* Save data in a database 
* append to a custom file on disk instead of a new file each form submission

**Comment by flaviocopes** [comment]
This is already possible. 
See http://learn.getgrav.org/advanced/forms#form-actions

In the form `process` field add your own processing action name, for example 'saveToDatabase'.

Then in your plugin listen for the event `onFormProcessed` https://github.com/getgrav/grav-plugin-email/blob/develop/email.php#L22 and provide a handler for the `saveToDatabase` action: https://github.com/getgrav/grav-plugin-email/blob/develop/email.php#L57. 

I posted those links that are from the Email plugin, it sends emails in this way, and you can add any action you can think of in your plugins / themes.
