### ISSUE TITLE
JS error in console when jQuery absent

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-form#290]
Hey,

Because of [this line of code]( https://github.com/getgrav/grav-plugin-form/blob/42ff44a07badc45e7516c5e10aa66c154ee849b1/templates/forms/default/form.html.twig#L39), javascript is broken and send an error in the client console:

```
Uncaught ReferenceError: jQuery is not defined
```

It's because of jQuery global. When a Grav project don't use it but use Grav plugin form, we get this error.

It could be nice to completely remove jQuery dependency, don't you think?

**Comment by drzraf** [comment]
Same here.
Doc' state that only the file field requires jQuery.
And depending on it to just combine a JS object with `{ PLUGIN_FORM: {} }` is not that legit.
As soon as we webpack/transpile/... there is many possibility that jQuery is simply not here.
