### ISSUE TITLE
form 3.0.0 beta-.5 wrong action/redirect after submit

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-form#318]
In my modular form.md I set
action:  /
After submitting it redirected me to the start/header of my homepage. I implemented a modal success box which shows the success message.
This was working in form 2.16.4
In form 3.0.0-beta.5 after formsubmit it redirects to /home/_contact which does not exist and results in an error 404,  page does not exist message. I tried different routes for action parameter, but it seems action setting not working anymore.

**Comment by mahagr** [comment]
Action should be fixed now.

**Comment by axel-rank** [comment]
Yes, working again!

**Comment by mahagr** [comment]
Made some extra fixes to allow modular forms to work without `action: /` in them. In that case, the form will be submitted using the current URL.
