### ISSUE TITLE
Class 'Grav\Plugin\Form\Form' not found

### ISSUE THREAD

**Issue by clemdesign** [getgrav/grav-plugin-form#328]
Hi guys,

I'm trying to fix an operational issue but I don't find the solution.

I upgraded my Grav site from 1.3.1 to 1.5.8 and all plugins.

For all plugins, I found a solution against malfunctions, with the exception of this one (Form).

When I use the plugin Form v2.16.4, with this [integration](https://learn.getgrav.org/15/forms/forms/example-form), my contact form doesn't display.

When I revert to Form v2.8.0 (last stable version), I have the error "Class 'Grav\Plugin\Form\Form' not found". The contact form no longer appears since v2.11.0. This error appears only on admin login page. I'm already tryed to reinstall plugin, or apply insensitive casses (git config core.ignorecase false)

When I go back to Admin Login v1.5.1 (last stable version), everything works corretcly but I'm not take advantage of the new tools in the admin panel.

Any idea about a solution please?

Thanks,

**Comment by mahagr** [comment]
Remove Login plugin and install it again. We renamed the file from `form.php` to `Form.php` and some filesystems thinks that it's the same name even if it's not.

**Comment by clemdesign** [comment]
I already tryied this solution but:
- using GPM: tool will install the last plugin Form v2.16.4 but my contact Form no longer appears.
- using manual installation with v2.8.0 or v2.10.0, the problem still appears.

**Comment by rhukster** [comment]
This actually looks like a PHP opcache issue, where your server is holding on to the cached classes.  Is it possible to toggle the PHP version or restart the webserver?

**Comment by clemdesign** [comment]
I use PHP 7.0.10. Is it possible this version cause this behavior?

To answer your question @rhukster , I'm using 2 systems:

- Local server, Windows based using Wamp
- Remote server, Linux based.

Both server use the same PHP version and the issue appears on both. For now, I can't upgrade PHP version because I have several site works on it.
I already tried to restart local server but the problem still appears.

> A piece of solution

In Plugin Admin, file `admin.php`, when I remove the line `use Grav\Plugin\Form\Form;`, the problem disappears with plugin-admin v1.8.19 and plugin-form v2.10.0. But if I use the last version of both plugins, the contact form still no longer appears.

**Comment by rhukster** [comment]
It could be. Php 7.0 is no longer supported and that particular version is very old too.  7.0.33 was the latest supported version.  I would recommend php 7.2 at this point and I personally run php 7.3.

**Comment by rhukster** [comment]
Bye the next version of grav that will be released shortly requires at least php 7.1.3

**Comment by clemdesign** [comment]
I upgraded Wamp and tested local site with PHP 7.2 and PHP 7.3, the contact form still no appears.

Between Grav v1.3.1 and 1.5.8, is there not an added or deleted configuration in Form plugin, Admin plugin, Blueprints or Grav System that could impact the display of a form?

**Comment by mahagr** [comment]
There have been quite many changes/fixes on form handling between those versions, maybe you're doing something in a way that was really not supported.

Maybe the best way to try to narrow this issue down is to try to figure out which versions (grav, form, admin all released around the same time). Most obvious points of time are minor releases (1.4, 1.5, 1.6...).
