### ISSUE TITLE
Captcha is ignored when JavaScript is not enabled

### ISSUE THREAD

**Issue by CodeAlDente** [getgrav/grav-plugin-form#329]
I am having a form configured with reCAPTCHA just like this:

```
name: g-recaptcha-response
label: Captcha
type: captcha
recaptcha_not_validated: 'Captcha not valid!'
validate:
    required: true
```

I am using the latest version of Grav (1.5.10) and the latest version of the form plugin (2.16.4) with the theme Big Picture (1.4.0).

`recaptcha_site_key` is stored in the plugin settings. When JavaScript is enabled everything works perfectly fine. But the captcha field disappears when JavaScript has been disabled and therefore no checks are made against spammers.

**Comment by CodeAlDente** [comment]
Is there any workaround?

**Comment by rhukster** [comment]
Recaptcha is supposed to add an extra field by JavaScript that is required to get submit the form.  I've not tested this, but it shouldn't work without JavaScript enabled.  Have you tested this and confirmed this?

**Comment by rhukster** [comment]
BTW, i tested this on a site running Captcha by disabling JS in devtools.  It didn't bypass the tests, and submission failed.

![Image 2019-04-07 at 10 32 56 PM](https://user-images.githubusercontent.com/1084697/55698872-3d91d280-5985-11e9-9d2d-f6d04faa0a9d.png)

**Comment by CodeAlDente** [comment]
It still does not work for me as my form submits still going through when I disable JavaScript. For now I moved to V3 of reCAPTCHA and as far as I can see (source code, console) it works. Could you share your form settings

**Comment by rhukster** [comment]
Does your theme have a bottom JS block?

```
{% block bottom %}
    {{ assets.js('bottom')|raw }}
{% endblock %}
```

This is required.  If not I suggest looking at the blog post about  the recommended theme changes for proper asset handling (CSS/JS):5

https://getgrav.org/blog/important-theme-updates

**Comment by CodeAlDente** [comment]
Last update of Big Picture (1.4.0) was more than a year ago and from what I can see it does not make use of the changes mentioned in that article. I guess I will go with Quark now as it is the default one and it looks quite similar to Big Picture.

Thank you!

**Comment by rhukster** [comment]
Quark is the best bet if you want to keep up with the latest and greatest.  Unfortunately "Big Picture" is a 3rd party theme that we don't control.  We updated all our Grav team themes with the recommended structure, but 3rd party folks have to do it themselves.

**Comment by CodeAlDente** [comment]
Yes I have just seen that. I will go with Quark then. Thank you very much for your help and all the effort! I appreciate that.
