### ISSUE TITLE
Error "Identifier 'user' is not defined"

### ISSUE THREAD

**Issue by brickcamp** [getgrav/grav-plugin-form#332]
Hi there,
first things first: Thanks for doing such an amazing job with grav and it's plugins - I love it!

But, last night, I had a lot of troubles with the releases of grav and the form plugin. After installing both of them, my site stopped working immediately by throwing this error message on every page:

**Identifier "user" is not defined.** 
![Bildschirmfoto-20190412220316-941x516](https://user-images.githubusercontent.com/49322756/56063159-c8e8da80-5d6e-11e9-8ff9-aa223a85553d.png)
[Download ZIP-file containing error page](https://github.com/getgrav/grav-plugin-form/files/3074988/Identifier-user-is-not-defined.html.zip)

Today, I came up with the solution: **I hadn't installed the login plugin** and system.session was set to false. I changed both of it and now everything works again.

So, please add a dependency to the "login" plugin. Or fix the coding there... 😄

**Comment by rhukster** [comment]
It's not really a login dependency, as form should not require anything else, however, it is a bug in Grav's trait to ensure that user is available.  Also, flash forms to support the ajax uploads will not work without a session, but I added a safety check so it does not error out.

https://github.com/getgrav/grav/commit/d502ff08c1ca1881dedb4b6f43480e4329c1afe8

**Comment by brickcamp** [comment]
Looks good - I removed the "dependency" thing from the issue title

**Comment by brickcamp** [comment]
Finally, I tested this now - this fixed it, thank you! 👍 Case closed
