### ISSUE TITLE
Site is not verifying reCAPTCHA solutions

### ISSUE THREAD

**Issue by superhu4** [getgrav/grav-plugin-form#344]
Using reCAPTCHA v. 2 – Invisible with the Form v. 3.0.2 plugin on Grav 1.6.8 with a theme based on Quark v. 2.0.0, forms submit successfully, but the reCAPTCHA dashboard warns:

> We detected that your site is not verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site. Please see our developer site for more information.

Not sure where to look to troubleshoot this. Thank you!

**Comment by rhukster** [comment]
What does your form look like in your page md file?

**Comment by rhukster** [comment]
Actually, think i found the error.  Was from a PR I accepted.

**Comment by CodeAlDente** [comment]
After upgrading Grav and the form plugin to the latest version, I am getting an error saying the site key is invalid. I am using Version 3 of reCAPTCHA along with the corresponding, correct key. It worked perfectly before. I have already tried to reset a new key but the error message remains.

**Comment by rhukster** [comment]
I'm using version 3 on several sites, so the only thing I would say is make sure you create a NEW api key/secret on the Google side of things for v3.  You can't use v2 keys with it.

**Comment by CodeAlDente** [comment]
I did create new keys and it did not work.

I am using Grav v1.6.9, Form plugin v3.0.3 and Quark theme v2.0.1. I have tested the example contact form here: https://learn.getgrav.org/16/forms/forms/example-form

Everything worked fine before. I have got that error message just after the update.

**Comment by rhukster** [comment]
Good catch.. fixed in develop
