### ISSUE TITLE
reset form after Submission

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-form#348]
how do this. Thx

**Comment by dimitrilongo** [comment]
just go to 
https://learn.getgrav.org/16/

everything about form actions

**Comment by abooks23** [comment]
i read this,
i add to form
    process:
            -
            reset: true
but it not work
form with ajax

**Comment by dimitrilongo** [comment]
maybe a simple
`$('#contact-form')[0].reset(); ` after ajax success

**Comment by abooks23** [comment]
yes, its work. thanks
