### ISSUE TITLE
Cannot upload file when $grav['user'] is not set

### ISSUE THREAD

**Issue by AndruePeters** [getgrav/grav-plugin-form#352]
Cannot upload file if $grav['user'] is not set.
Issue is on Grav 1.6.9 and 1.6.10. These are the only two versions I tested.

Fix is to change code in https://github.com/getgrav/grav-plugin-form/blob/develop/classes/Form.php on line 641 to

```php
// We need to store the file into flash object or it will not be available upon save later on.
  $flash = $this->getFlash();
  if (isset($grav['user'])) {
    $flash->setUrl($url)->setUser($grav['user']);
  } else {
    $flash->setUrl($url);
  }
```

This also works:
```php
$flash->setUrl($url)->setUser($grav['user'] ?? null);
```

This is with the fix:
<img width="1329" alt="Screen Shot 2019-06-17 at 1 39 49 PM" src="https://user-images.githubusercontent.com/5511409/59624733-901a0880-9105-11e9-8f6b-5a0313b74669.png">

This is without the fix:
<img width="1329" alt="Screen Shot 2019-06-17 at 1 40 29 PM" src="https://user-images.githubusercontent.com/5511409/59624764-a32cd880-9105-11e9-9aad-d21f591c6dd8.png">

I am not familiar with handling sessions with grav, but a comment in #332 says a session is needed. This works with `system.session.enabled = false`.
Also, is this maybe the issue for #349 ?

**Comment by rhukster** [comment]
Looks like a decent fix.. @mahagr was working on some form updates recently related to flash storage, so be good for him to take a look.

**Comment by mahagr** [comment]
Looks like I missed that one. Fixed now. I also found some other similar issues, will add checks against them, too.
