### ISSUE TITLE
chage file save folder?

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-form#353]
Hi
can I save data from form to another place different from `user/data`
eg
 form call from `page01` and data will be saved in this folder

**Comment by rhukster** [comment]
The save location of `user/data` is based on the  `user://data` stream.  So not really.

If you are interested, you can see this in the code here: https://github.com/getgrav/grav-plugin-form/blob/develop/form.php#L557-L559

It is normal behavior for Grav to store all user data inside `user/data`.  You could, however, create your own plugin to listen to a custom action, with an `onFormProcessed()` event, and use the same save logic, but change the location to wherever you want.  Grav is very flexible like that.

**Comment by mahagr** [comment]
Actually, I've changed this to use `user-data://` stream which can easily be relocated. Though there are likely still places using the old location (like this one).
