### ISSUE TITLE
Refresh prevention is oversensitive in register form

### ISSUE THREAD

**Issue by newbthenewbd** [getgrav/grav-plugin-form#354]
**Testing platform:** Arch Linux with nginx 1.16.0-1 and php-fpm 7.3.6-1

**Steps to recreate:**
1. Start with a clean Grav install from https://getgrav.org/download/core/grav-admin/1.6.11, set up an admin account and update the installation as needed
2. Copy `/user/plugins/form/form.yaml` to `/user/config/plugins`
3. Copy `/user/plugins/login/login.yaml` to `/user/config/plugins`
4. Set `refresh_prevention` to `true` in `/user/config/plugins/form.yaml`
5. Enable `user_registration` in `/user/config/plugins/login.yaml`
6. Navigate to `localhost/or/wherever/grav/is/user_register`
7. Register an user
8. Navigate to `localhost/or/wherever/grav/is`, then again to `localhost/or/wherever/grav/is/user_register`, without using the back button
9. Try registering a different user

**Expected result:** The different user is successfully registered

**Actual result:** _This form has already been submitted._

**Comment by mahagr** [comment]
This is actually a bug which I found a few days ago.
