### ISSUE TITLE
dependent on other fields

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-form#357]
How to made fields dependent other 
eg: if field 1 had value A - will be render field 2,
if field 1 had value B - will be render field 3,
if value C - render field 4
...
it is possible?

**Comment by mahagr** [comment]
With JavaScript. :)

**Comment by rhukster** [comment]
Currently there's no server-side (ie, Grav) way of doing this, you need to do it in the browser at run time with javascript.

**Comment by abooks23** [comment]
thanks)
