### ISSUE TITLE
Not sending emails from forms if supported languages (de, en) in configuration is filled

### ISSUE THREAD

**Issue by matthias7719** [getgrav/grav-plugin-form#361]
Hello
The same bug every time with a running and also a fresh installation from Grav.
Everything works fine with the example contact form from the Grav documentation.
Message was sent, also the green Thankyou screen comes up and my inbox was filled with the message.
But after setting values in my configuration for supported languages (de, en) nothing happens anymore - no error, no Thankyou screen and also nothing in my inbox. After deleting values for supported languages everything works fine again. So I think there is a problem between Grav configuration and the form plugin. Renaming form.md and also formdata.md to form.de.md and formdata.de.md —> no effect.

Thank you in advance for help.

Kind regards

Matthias

**Comment by rhukster** [comment]
Do you mind looking at this one too @mahagr ?

**Comment by matthias7719** [comment]
Development version (3.0.8) fixed my problem. Solved.
