### ISSUE TITLE
How to get TmpDir from other plugin?

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav-plugin-form#362]
Recently I was able to update my [Add Page by Form Plugin](https://github.com/bleutzinn/grav-plugin-add-page-by-form) after it broke with the release of Grav 1.6 and changes to the Form Plugin.

A new issue ([#44](https://github.com/bleutzinn/grav-plugin-add-page-by-form/issues/44)) is caused by the removal of the `getSessionTmpDir()` function.

Since I don't understand the working and the code of the Form plugin I need help on this. 
Can and if so how, should the new function `getTmpDir()` be used from another plugin? Or should I use another way?

My code fragment currently is ([line 315-317](https://github.com/bleutzinn/grav-plugin-add-page-by-form/blob/master/add-page-by-form.php#L317)):

```
// Get current tmp dir
$this->session_id = $this->grav['session']->getId();
$tmp_session_dir = FormFlash::getSessionTmpDir($this->session_id);
```

**Comment by mahagr** [comment]
Sorry from breaking your plugin and long delay on my response (I had a short vacation and was too busy afterwards).

The reason why the method was removed is that we needed a better way to control where to store the temporary data; one example is to store form state into users own folder, allowing us to store form state and restore it in the new session. This means that there is no global location anymore and you need to look into the form to find it.

I don't think you need that code anymore; Form will now keep all the uploaded files in a temporary location allowing you to move them when you're doing the save. There are multiple ways to do that, one being to hook into an event.

Ping/PM me on Discord; I think it is faster way to look into this.

**Comment by mahagr** [comment]
@bleutzinn I've not heard back from you. I think that it is safe to just remove this code in newer Grav versions as Grav already keeps the files in temporary location until you save.

**Comment by bleutzinn** [comment]
@mahagr, sorry for not getting back to you. Lots of reasons why.
A pull request by @tranduyhung made me realise which code wasn't needed anymore.
Thanks!
