### ISSUE TITLE
Validator error

### ISSUE THREAD

**Issue by HarDX** [getgrav/grav-plugin-form#376]
When i check site by validator w3 org i have error:
Duplicate ID contact.
From line x, column x; to line x, column x
     ↩↩↩↩↩<form name="contact"↩      action="/home"↩      method="POST"↩      id="contact"            class=" "↩                  >↩↩  ↩ 

In form.html.twig i found
```
<form name="{{ form.name }}"
      action="{{ action | trim('/', 'right') }}"
      method="{{ method }}"{{ multipart }}
      {% if form.id %}id="{{ form.id }}"{% endif %}
```
how i can set it different form.id and form.name?

**Comment by rhukster** [comment]
Directly in your form yaml where the form is defined, usually this is in a page. 

https://learn.getgrav.org/16/forms/forms/example-form

**Comment by HarDX** [comment]
I found error i have one of div id as contact - sorry
