### ISSUE TITLE
Disabling client side validation in plugin's config doesn't work

### ISSUE THREAD

**Issue by SeriousKen** [getgrav/grav-plugin-form#378]
Disabling client side validation globally in `form.yaml` doesn't seem to work. It works only when defined in the frontmatter on each form.

Using Grav 1.6.16 and Form v3.0.9

**Comment by SeriousKen** [comment]
This is still an issue in Form v4.3.0

**Comment by NicoHood** [comment]
This is fixed in the latest development branch:
https://github.com/getgrav/grav-plugin-form/pull/482

**Comment by NicoHood** [comment]
You can close this now. Its fixed in the latest version
