### ISSUE TITLE
Checkbox field superfluous label tag

### ISSUE THREAD

**Issue by jeifour** [getgrav/grav-plugin-form#402]
I was adding a checkbox to my form when I noticed additional whitespace above it. I looked in the rendered HTML and it looks like this:

```
<div class="form-field ">
  <div class="form-label"><label class="inline"></label></div>
  <div class="form-data" data-grav-field="checkbox" data-grav-disabled="" data-grav-default="null">
    <div class="form-input-wrapper  ">
      <input name="data[tos_check]" value="" type="checkbox" id="tos_check-" class="">
      <label style="display:inline;" class="inline" for="tos_check-">I agree to the TOS.</label>
    </div>
  </div>
</div>
```

So the whitespace is caused by the first child div element. When I looked at the plugin code, it seems like in https://github.com/getgrav/grav-plugin-form/blob/217fa99fd863111a4fe3d67375de29bbcdd041bb/templates/forms/fields/checkbox/checkbox.html.twig#L3 you are setting the label block to empty, but I would've expected that it should vanish completely, because the actual label comes later.

For now I just set display_label to false, because I noticed that this option exists when looking at https://github.com/getgrav/grav-plugin-form/blob/217fa99fd863111a4fe3d67375de29bbcdd041bb/templates/forms/default/field.html.twig#L60 (and it is actually also in the documentation), but even if that's the intended way to use the checkbox field, it is a bit strange naming when you have to set display_label to false, but you also have a label property that is actually rendered. Personally I don't see the point in the empty label existing at all.

But maybe also I'm doing something wrong in my setup, so it would be great if you could check this out.

**Comment by rhukster** [comment]
This is a bit of a limitation based on maintaining backward compatibility.  We can't really move the label block at this point without potentially breaking sites.  So the workaround is the `show_label` option as you have already found.  Alternatively, you can remove the whitespace by using CSS.

**Comment by jeifour** [comment]
Ok thank you for taking the time to comment on this. I'll keep using the workaround then.
