### ISSUE TITLE
Release to address security vulnerabilities?

### ISSUE THREAD

**Issue by RCheesley** [getgrav/grav-plugin-form#414]
We have had some warnings about security vulnerabilities via Github, will there be a release coming soon to address them? I can list them out if that would be helpful!

**Comment by rhukster** [comment]
These JS ones?

**Comment by rhukster** [comment]
If so, you can just gitignore the `yarn.lock` file to remove/ignore those security vulnerabilities messages. I've recompiled the JS anyway with latest.

**Comment by RCheesley** [comment]
If you'd intended a screenshot it didn't attach, but yes I think they were a bunch of JS related ones - as our repo is public now, we started getting notifications and dependabot PR's :)
