### ISSUE TITLE
Form data are not sent if the input is within "Section"

### ISSUE THREAD

**Issue by ondrejvysek** [getgrav/grav-plugin-form#417]
I have a form including form section. as a result, I want to send an email. Unfortunately, inputs (checkboxes) within the section are not sent out. I can see that data is posted and are within the FormData header.

even used Dump function on variables, items within the type:section returns null if they are checked, or missing if unchecked.
```
    "namefirstlast" => "Name"
    "email" => "email"
    "tel" => "+42000000"
    "company" => "company"
    "address" => "Adderess"
    "usercount" => "222"
    "servicetype" => "service 1"
    "use" => null (checked checkbox within section)
    "learn" => null (checked checkbox within section)
    "haveo" => "1" (checked checkbox outside section)
    "gdpr" => "1" (checked checkbox outside section)
    "mca" => "1" (checked checkbox outside section)
    "pot" => ""
```

Any ideas?

**Comment by mahagr** [comment]
@ondrejvysek Please provide example blueprint which can be used to test this.

**Comment by ondrejvysek** [comment]
here it is
[form.en.txt](https://github.com/getgrav/grav-plugin-form/files/4522054/form.en.txt)
result: [feedback-20200423-130734-121845.txt](https://github.com/getgrav/grav-plugin-form/files/4522058/feedback-20200423-130734-121845.txt)
what was filled in the form: ![Capture](https://user-images.githubusercontent.com/29834082/80092975-fc566b80-8563-11ea-85b1-011e0f5a1d27.JPG)

header:
ata[namefirstlast]: Test User
data[email]: email@email.com
data[tel]: 123456789
data[subject]: Message Subject 
data[message]: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
data[usercount]: 300
data[servicetype]: teams
data[useteams]: 0
data[secureteams]: 0
data[haveo365]: 0
data[gdpr]: 
data[formname]: web-Contact
data[pot]: 
__form-name__: order
__unique_form_id__: jypiqpox7iy53elg1b0u
form-nonce: 6a1b2d0dc5cddc5a2a214b1502d229a1

**Comment by rhukster** [comment]
Checkboxes are only sent if they are 'checked'.  There are some hacky ways to get around this however: https://stackoverflow.com/questions/1809494/post-unchecked-html-checkboxes

![Image 2020-04-23 at 8 30 46 AM](https://user-images.githubusercontent.com/1084697/80111225-dd90ae80-853c-11ea-849f-caa5241aa4ad.png)

I tested your form, and 'set' values are sent...

**Comment by anton-mellit** [comment]
In a related situation I was advised to add
```
validate:
    type: bool
```
to my checkbox fields and it started to save their values as true/false in both set and unset situations. I don't know if this is documented.
