### ISSUE TITLE
Ability to display form midway through page content

### ISSUE THREAD

**Issue by cg433n** [getgrav/grav-plugin-form#42]
Kind of like this:

```
Content
{{ show form here }}
More content
```

**Comment by flaviocopes** [comment]
Right now this is possible through modular pages learn.getgrav.org/advanced/forms#using-forms-in-modular-pages

**Comment by cg433n** [comment]
I wonder if it's possible to do: ```{% include "forms/form.html.twig" %}``` midway through the page's content, (with twig processing enabled). Last time I tried this, the form would display, but not process.

**Comment by rhukster** [comment]
This will be possible with the upcoming Forms 2.0.  Currently available for testing in this PR:

https://github.com/getgrav/grav-plugin-form/pull/85

**Comment by rhukster** [comment]
Forms 2.0 released.
