### ISSUE TITLE
Formdata template and Here is the summary of what you wrote to us

### ISSUE THREAD

**Issue by rhubarbselleven** [getgrav/grav-plugin-form#426]
So the formdata.html.twig template is great. It is to the point and nicely repeats the information back to the user. I can supply my own content to introduce the page yet there's this one funky line:

```
<p>{{ 'PLUGIN_FORM.DATA_SUMMARY'|t }}</p>
```
The value of `DATA_SUMMARY` is: Here is the summary of what you wrote to us

I understand that I can either override the template or supply a new language value to supply content here but does this line actually need to be here?

I feel not as there is sufficient support in the tempate for this type of messaging. Alternatively, the template can be overridden to add this type of messaging in those use cases.

**Comment by NicoHood** [comment]
How would you trigger this bug? I've set

```yaml
- message: 'thanks for submitting'
- reset: true
```

and no other message is shown (using the comments plugin)

**Comment by w00fz** [comment]
I think it is good to have there as a basic example of form data template that showcase how you can override, use html and include translations.

Really the point is that you either override it yourself or change language. As it is by default, relying purely on the echo of the data, is really not something you would or should do on a live site. Most likely you will be wanting a more robust layout and output than that.
