### ISSUE TITLE
400 error after submiting contact form

### ISSUE THREAD

**Issue by lupinehorror** [getgrav/grav-plugin-form#43]
hi all.
have just setup a simple site and have used the [standard contact form](http://learn.getgrav.org/advanced/contact-form).
added my recaptcha keys, setup the email addresses and the form displays fine.
however when i enter the required details and click submit it throws an error 

'400 - Display page not found. Please check the page exists'

and the log shows

'[2016-02-05 06:43:52] grav.CRITICAL: Display page not found. Please check the page exists. - Trace: #0 [internal function]: Grav\Plugin\FormPlugin->onFormProcessed(Object(RocketTheme\Toolbox\Event\Event), 'onFormProcessed', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #1 '

the form details are sent as they should be. can't figure out why, after hitting submit, the contact form doesn't display 'message: Thank you for getting in touch!' as it should.
apologies if i'm missing something obvious. rather new to this platform (but i'm loving it so far)

**Comment by hugoaf** [comment]
Did you perform this step?
> Now inside the page folder create a subfolder named thankyou/, create a new file named formdata.md. Users submitting the form will be redirected on that page
> The formdata page template is provided in Antimatter and other themes. If your theme does not provide it, you'll see an error. You can just copy it from Antimatter and things should work fine.

**Comment by lupinehorror** [comment]
ah.
feel like a bit of a fool now (that happens more often than i'd like).
have got rid of the 400 error but will need to tweak a fair bit more. i do appreciate your assistance.
