### ISSUE TITLE
Add attributes (like Tabindex)

### ISSUE THREAD

**Issue by johBerlin** [getgrav/grav-plugin-form#433]
Hello Form-Plugin-People,

I wonder if there is a way to define the tabindex of a form field.
My problem is, I added a customized checkbox and now going through the form is not as fun with the tab-key of my keyboard ;-)

Can you help?

BW

**Comment by ricardo118** [comment]
there is exactly that
you can look on the template and see

`{% if field.tabindex %}tabindex="{{ field.tabindex }}"{% endif %}`

**Comment by johBerlin** [comment]
ah cool - so I can use the attrubute "tabindex" in the frontmatter?

**Comment by ricardo118** [comment]
yeah should work in all fields

**Comment by johBerlin** [comment]
lovely! TKS
