### ISSUE TITLE
Text value for fieldset type is not parsed properly

### ISSUE THREAD

**Issue by PixelT** [getgrav/grav-plugin-form#449]
**Step to reproduce:**
1) Create `fieldset` type field in blueprint
2) Provide `text` for this field
3) Check this field (effect) on admin panel

**Example:**
```
header.fieldset:
  type: fieldset
  title: Your title
  help: Help text
  info: Info text
  text: Text inside fieldset and before other fields
```

**Actual result:**
![image](https://user-images.githubusercontent.com/6519351/95653303-04956980-0af8-11eb-8dd2-001b84bc137d.png)

**Expected result:**
Text is displayed properly in `<p>` element

**Issue exist on:**
- Grav v1.6.28
- Admin v1.9.17
- Form v4.1.2

**Comment by OleVik** [comment]
The issue has been replicated, and is only applicable to Admin. Solved by [Admin #1956](https://github.com/getgrav/grav-plugin-admin/pull/1956).
