### ISSUE TITLE
Section field uses h1

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-form#453]
https://github.com/getgrav/grav-plugin-form/blob/eeaa89f89015410c425f09d9d41f7b171dc9f36d/templates/forms/fields/section/section.html.twig#L7

The section field uses h1 by default. This is a really bad idea, as a page should not have more then one h1. Also most likely you will have a different h1 for the page, maybe a h2 after and a h3 inside the section. The reason why this is important is search engine optimization (SEO).

I know this template can be overwritten in the theme, but I'd like to fix it upstream, if possible. My suggestion:
* Change the new default to `h3`
* Introduce an optional field setting `title_level` which can be set to `h4` etc.

```html
<{{ field.title_level|default('h3') }} class="{% if not field.underline %}no_underline{% endif %}">{{ field.title|t }}</{{ field.title_level|default('h3') }}>
```

The change only affects frontend from, not the admin. The admin also uses h1, but does not need a search engine optimization, so it is less important.

**Comment by rhukster** [comment]
This is probably a better idea, however, this field is primarily used in Admin, where h1 was already styled the way we wanted.  Also changing it now would mean a breaking change.  So something we'll handle better next time.

As a workaround you can override the `section.html.twig` and change your end.

**Comment by NicoHood** [comment]
The admin template is located here, will this be pulled from the forms plugin?:
https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/templates/forms/fields/section/section.html.twig

What about this? It is **100% backwards compatible,** but still fixes the issue:

```
<{{ field.title_level|default('h1') }} class="{% if not field.underline %}no_underline{% endif %}">{{ field.title|t }}</{{ field.title_level|default('h1') }}>
```

**Comment by mahagr** [comment]
@rhukster ?

**Comment by rhukster** [comment]
I'm ok with this if you create a PR.

Cheers!
