### ISSUE TITLE
Form message class issue

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-form#469]
When adding a form message there is an issue with its scope vs type. The message is shown in black instead of green:
```
<div class="toast toast- success">
            <i class="icon dripicons-"></i> Vielen Dank für deine Bewertung! Wir haben dir soeben eine Bestätigungsemail gesendet. Um deine Bewertung auf der Website anzuzeigen, klicke bitte auf den Bestätigungslink in der E-Mail.
        </div>
```

This is my [messages.html.twig](https://github.com/getgrav/grav-theme-quark/blob/develop/templates/partials/messages.html.twig):
```html
{% set type_mapping = {'info':'success', 'error': 'error', 'warning': 'warning'} %}
{% set icon_mapping = {'info':'checkmark', 'error':'wrong', 'warning':'information'} %}

{% if grav.messages.all %}
    <div id="messages">
    {% for message in grav.messages.fetch %}

        {% set scope = message.scope|e %}
        {% set type = type_mapping[scope] %}
        {% set icon = icon_mapping[scope] %}

        <div class="toast toast-{{ type }} {{ scope }}">
            <i class="icon dripicons-{{ icon }}"></i> {{ message.message|raw }}
        </div>
    {% endfor %}
    </div>
{% endif %}
```

For "normal" messages added via plugin this works fine. The correct html would be `<div class="toast toast-success">` (without space). This is NOT a whitespace issue, for some reason type and scope seem to be switched.

Edit: It is possible that this is a quark theme template issue. Maybe `success` is a valid scope, but quark does not implement it. Also the icons are broken by the way...

**Comment by NicoHood** [comment]
I found that the following line is causing the issue:
https://github.com/getgrav/grav-plugin-form/blob/develop/form.php#L495

Is `success` a valid message type? If not, it must be `info`. As [stated here](https://github.com/getgrav/grav-learn/issues/356#issuecomment-737463342) the message API really needs some more documentation.

**Comment by rhukster** [comment]
It's a hold over from when we had the Antimatter theme that did use the success class.  Really this is why it's not good to have any CSS reliance on themes.  The current implementation of the form plugin has a fair bit of backward-compatibility complexity.  I can't improve things too much because it has the potential of breaking currently installed sites that assume the form functionality (and templates) are going to be compatible when updated.

This is something I plan on revamping completely in Form2 plugin.

**Comment by mahagr** [comment]
The code cannot be changed as it breaks existing sites which all assume the current behavior. The fix needs to be in the theme.
