### ISSUE TITLE
form.message does not have type ?

### ISSUE THREAD

**Issue by changwuf31** [getgrav/grav-plugin-form#47]
how can one differentiate success messages, from failure ones ?

**Comment by flaviocopes** [comment]
This should be added, when there's a problem add a `messageType = 'error'` information that can be passed to the template.

**Comment by rhukster** [comment]
I've sort of changed this a little for latest beta.  Any time an `onFormValidationError()` event is processed there is a `form.message_color` set to `red`.  Default is `green`.  If you have markdown notices set, this will output a nicely formatted error.
