### ISSUE TITLE
Internationalization Issue

### ISSUE THREAD

**Issue by nsierram** [getgrav/grav-plugin-form#5]
When using the internationalization options there's a problem when submitting forms.

In templates/forms/default/form.html.twig line 4, we have the following:

      action="{{ uri.rootUrl ~ (form.action|default(page.route)) }}"

The thing is that even if you set (in system.yaml)

    languages.home_redirect.include_lang: true
    languages.home_redirect.include_route: true
the page.route will give the url without the locale, so when you submit the form, you get a 404.

The other error is that the include_route only works with the home alias, but i reckon that issue belongs to grav.

**Comment by flaviocopes** [comment]
@rhukster in your opinion should page.route include the lang code? Or should uri.rootUrl? Or should we add a separate method to Uri that returns the root url including the lang?

**Comment by nsierram** [comment]
Just for those in this situation, it's possible to avoid the 404 setting the form.action value in the YAML frontmatter of the page as the name of the route.
For example my form is in
mysite.local/en/contact (where en is the language code).
So for the file that renders the above route (i.e. form.en.md) add the value form.action: contact
For example for italian translation my route is
mysite.local/it/contatti as I have set the slug as contatti, so set form.action: contatti
And so on.

**Comment by rhukster** [comment]
`page.route()` should definitely not have the lang code forced.  

Better option would be to use `page.url()` as this will prefix with the lang code.  Can someone test that?

**Comment by rhukster** [comment]
So how about changing the `action` line in the `plugins/form/templates/forms/default/form.html.twig` file to:

```
action="{{ form.action ? base_url ~ form.action : page.url }}"
```

**Comment by bovisp** [comment]
@rhukster . This seems to have solved my problem as I outlined it in Gitter earlier today.
