### ISSUE TITLE
Form shown in a language different than the page language

### ISSUE THREAD

**Issue by marcocevoli** [getgrav/grav-plugin-form#507]
Often times I see the form on our website rendered in a language different than the page language. The site is https://qabiria.com. 
To reproduce it, I did the following: open the home page (without language suffix) in a browser whose first language is not Italian (I tried with Spanish).

The Spanish home page shows up, then you go to Contacto, the correct contact page in Spanish shows up, but if you click on the language switcher (bottom right) and choose Italiano, the page switches to Italian, but the actual form is in Spanish. When I empty the cache from the back-end, then the issue goes away…

It's probably related to other issues mentioning language, such as https://github.com/getgrav/grav-plugin-form/issues/492 but I don't know how to troubleshoot. 

Setting `cache_enable: false` doesn't solve the issue.

**Comment by mahagr** [comment]
I am assuming that you have variations of the same form in each of the markdown language variants?

**Comment by marcocevoli** [comment]
You can download the exact code I'm using here: https://qabiria.com/form-error.zip The form is defined in the frontmatter of each md page and yes, it's the same form with different labels.

**Comment by mahagr** [comment]
I cannot reproduce the issue with your pages (changed the type to form) -- changing language also changes the form language (cache turned on). Page caching takes current language into account, so all the cached content (including forms) should also be cached per language -- which I verified by the debugger.

I would take a look into your twig template as it's likely caching the content.

**Comment by marcocevoli** [comment]
The issue was probably caused by the fact that the 3 forms shared the same name. I've changed that and apparently they're working fine now, but I still don't understand how the twig template calls each form (I need to better study the documentation). Thanks for helping me pinpoint the issue.

**Comment by mahagr** [comment]
Yeah, you cannot use the same name for different forms. Forms are kind of global in Grav and it uses the one it finds the first -- especially if the form isn't defined in the page itself (such as using modular).
