### ISSUE TITLE
Typo in recaptcha_secret variable at line 421

### ISSUE THREAD

**Issue by giminni** [getgrav/grav-plugin-form#509]
There is a typo in form.php (See below)

https://github.com/getgrav/grav-plugin-form/blob/3b2fdef73f3f6a43749fa3657b910107d1af2224/form.php#L421

**Comment by rhukster** [comment]
Actually that is intentional to catch an older typo :).  Basically we had a few releases with `recatpcha_secret` typo, so this catches that case.

**Comment by NicoHood** [comment]
I guess this is a perfect example of where adding a comment in the code would make a LOT of sense?
