### ISSUE TITLE
recatpcha vs recaptcha?

### ISSUE THREAD

**Issue by eXpl0it3r** [getgrav/grav-plugin-form#51]
Having troubles with the verification of the recaptcha request (I'm just getting `b:0;` as response from Google), I was going through the code and noticed that some of the variables use re**catp**cha instead of re**capt**cha. Is that intentional?

Occurrences:
* `recatpcha_secret`
* `recatpcha_site_key`

**Comment by flaviocopes** [comment]
Thanks for reporting! They are also referenced in the documentation with the typo. 

Will fix them in both the docs and in the code, still allowing the value with the typo so backwards compatibility is preserved.

**Comment by eXpl0it3r** [comment]
Yeah it's all over the place which made me wonder if it was intentional. :smile:
