### ISSUE TITLE
NONCE_NOT_VALIDATED message needs revision

### ISSUE THREAD

**Issue by aricooperdavis** [getgrav/grav-plugin-form#513]
The [`NONCE_NOT_VALIDATED` message](https://github.com/getgrav/grav-plugin-form/blob/16c0e9d1585dff625a2893fca18adfab25c0f5e9/languages.yaml#L4) is currently:

`"Oops there was a problem, please check your input and submit the form again."`

This advice doesn't work if the form was submitted via AJAX as the form nonce won't have changed so resubmitting the form will cause the same error. I'm not even convinced that the form nonce changes if the form is POSTed normally, but haven't experimented with this. I suggest we revise this message to something like:

"Oops, your form has timed out, please reload the page and submit the form again."

As this prompts the user to reload the page, thereby regenerating the forms unique ID.

**Comment by mahagr** [comment]
I like the proposal as it tells what really happened (regardless of AJAX or not).

**Comment by rhukster** [comment]
I agree, that's a better message, more accurate and useful.
