### ISSUE TITLE
Can't access theme options since grav 1.7.19

### ISSUE THREAD

**Issue by grimnebluna** [getgrav/grav-plugin-form#528]
Hi,

I've got a strange error since the update to grav 1.7.19:

`Argument 4 passed to Grav\Plugin\Form\TwigExtension::prepareFormField() must be of the type array, null given, called in /home/****/****/cache/twig/e1/e1c19b537f943e3c2da59d00cbbb0bac95bb2882df307317d9a0fed91f884da5.php on line 217`

The affected lines seem to be:

/user/plugins/form/classes/TwigExtension.php

```
   {
        // Make sure that the field is a valid form field type and is not being ignored.
        if (empty($field['type']) || ($field['validate']['ignore'] ?? false)) {
            return null;
        }
 
        // Check if we have just a list of fields (no name given).
        if (is_int($name)) {
            $name = null;
        }
 
        // Make sure that the field has a name.
        $name = $name ?? $field['name'] ?? null;
        if (!is_string($name) || $name === '') {
            return null;
        }
 
        // Prefix name with the parent name if needed.
        if (str_starts_with($name, '.')) {
            $name = $parent ? $parent . $name : (string)substr($name, 1);
```

Did others have this error or does it have to do with my themes blueprints.yaml?

Thanks in advance.

**Comment by grimnebluna** [comment]
So i have a hotfix which hopefully doesn't do any damage:

/classes/TwigExtension.php line 71

`    public function prepareFormField($field, $name = null, $parent = null, array $options = []): ?array
`
to

`    public function prepareFormField($field, $name = null, $parent = null, $options = []): ?array
`

any comment on if this affects grav in any way?

**Comment by mahagr** [comment]
Please check https://github.com/getgrav/grav-plugin-admin/commit/2f9b0a179c8875ceb058bec4da902a2fc719fda0
