### ISSUE TITLE
Math Captcha. x Multiplication operator works incorrectly.

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#587]
On every multiplication I can't pass math captcha.

for example:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/7556290/209470843-cb1552ed-3310-416d-ad40-6743e24b1b8e.png">

Result:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/7556290/209471031-6a0247d4-5b3c-471f-ab26-e09fe166c06c.png">

As a temporary solution, I disabled multiplication, addition and subtraction work well.

**Comment by beamaria** [comment]
Same problem here: validating by multiplication fails!

**Comment by rhukster** [comment]
It's a bug, but a super easy stupid one on my part, can you spot what's wrong?

https://github.com/getgrav/grav-plugin-form/blob/develop/classes/BasicCaptcha.php#L43

**Comment by beamaria** [comment]
Ah, ah, ah!! Lucky you that Santa has already left the gifts. otherwise... Are you going to correct it in the next plugin version??

**Comment by rhukster** [comment]
Fixed for next release
