### ISSUE TITLE
Note for the future: remove the `datetime` field

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav-plugin-form#60]
Moved to the Admin plugin since it's not meant for the frontend.

Kept in the Form plugin for the time being, to avoid issues with releases sync.

**Comment by rhukster** [comment]
I've changed datetime to extend text. This lets us keep it there for backwards compatibility and it will 'work' as text until we implement a proper solution.

**Comment by johannesE** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime marked the datetime field as deprecated. 

`datetime-local` however, is the way to go.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

Why did you remove datetime support and how can I get that field to work with grav-plugin-form?
