### ISSUE TITLE
Markdown editor form

### ISSUE THREAD

**Issue by Ho33e5** [getgrav/grav-plugin-form#67]
I have seen that grav-plugin-admin uses form as a backend and thus it extends the form plugin with a markdown editor.. It would be possible to integrate back this page editor as a form field. (my use case is a kind of wiki build on top of grav)

_please add label:enhancement_

**Comment by rhukster** [comment]
We really want to keep forms plugin fairly basic with a core set of fields, we may add a very simple editor field (not as powerful as the one in admin), but this might not suit your needs.

Really there is nothing stopping you copying the editor field, or create your own based on it, in your wiki plugin.  That's the great thing about the form fields, they are really just Twig.  I suggest you take this approach and then you can use whatever you like.  

I'll leave this ticket as an enhancement request, but it probably wont happen quickly.

**Comment by Ho33e5** [comment]
Okay! I may send a pr if i come up with something (or as you said, start a wiki plugin).
