### ISSUE TITLE
Ability to get client IP address

### ISSUE THREAD

**Issue by aiso-net** [getgrav/grav-plugin-form#70]
I would like to request the ability to get client IP address who is filling out the form and submitting it. We get a lot of form spam even with the google captcha enabled and want to block the IP addresses from our site, but cant since we dont know the form submitter's IP address. Would like a way to add a form field to the form data that is emailed to us that contains the submitter's IP address

**Comment by rhukster** [comment]
This might already be possible, i'll check..

**Comment by aiso-net** [comment]
Great, I hope so.

**Comment by rhukster** [comment]
Ok, we have better support for this coming in Grav 1.1 and Forms 1.3 beta, but until then the only way to do this is to add it manually in the Twig that is used for the email.  

1. Copy `user/plugin/form/templates/forms/default/data.html.twig` to your theme under `templates/forms/default/`
2. Add at the bottom: `User IP: {{ uri.ip() }}`

With Forms 1.3 you will be able to create a hidden form field with `data-default@: '\Grav\Common\Uri::ip'`

**Comment by rhukster** [comment]
Actually also added a nice **process action** for next beta release that lets you automatically do this by just having:

```
process:
    ip:
        label: User IP Address
```

**Comment by aiso-net** [comment]
Awesome, thanks so much!

**Comment by paulobrien** [comment]
It's not clear how this works... if I use process / ip, where does this end up? How do I include it in the form emailed on? Thanks!

**Comment by flaviocopes** [comment]
`process.ip` adds a `ip` value to the form saved data. So, it will be automatically added to the data in the email, if you put it after the `process.email` line in your form definition.
