### ISSUE TITLE
support onsubmit value to provide custom validation

### ISSUE THREAD

**Issue by rvalkenaers** [getgrav/grav-plugin-form#73]
Hi,

Would it be possible to support a value for onsubmit. This way we can provide some custom js to validate the form.

The standard html5 validation doesn't seem to work in safari.

**Comment by flaviocopes** [comment]
We could include Webshim or a similar polyfill solution for Safari https://stackoverflow.com/questions/32684657/safari-is-not-acknowledging-the-required-attribute-how-to-fix-it/34090932#34090932, as incredible as it might seem, it does not support required nor email fields validation

**Comment by rvalkenaers** [comment]
Webshim seems to do the trick.

Thanks!

**Comment by rvalkenaers** [comment]
I guess webshim doesn't support validation of google recaptcha?
