### ISSUE TITLE
Support for fetching form content by id/slug

### ISSUE THREAD

**Issue by ardkevin84** [getgrav/grav-plugin-form#77]
An enhancement to the plugin to allow us to fetch a given form's rendered content from twig, and render in place anywhere. Something like (in php) `$forms->get("_formslug_or_route")` which returns a reference to the renderable/workable form object. 

ideally, it returns a reference to the renderable object, as the form's action or other properties may need to be manipulated to work page-agnostic.

**Comment by rhukster** [comment]
i've implemented something similar for the upcoming forms 2.0 release.  Available for testing in the https://github.com/getgrav/grav-plugin-form/tree/feature/multiple_form_handling branch

**Comment by rhukster** [comment]
Actually created a PR: https://github.com/getgrav/grav-plugin-form/pull/85
