### ISSUE TITLE
Modular Forms not shown when shortcode-core plugin is installed

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#80]
Hello!

I tried to change Simpleform to Form plugin in Gravstrap theme. I followed the instructions here:
https://learn.getgrav.org/forms/forms/how-to-forms-in-modular-pages

Also use this skeleton as main example:
https://github.com/getgrav/grav-skeleton-deliver-site

I copied this folder:
https://github.com/getgrav/grav-theme-deliver/tree/develop/templates/forms

And add this content in modular md file:
```md
form:
    name: my-nice-form
    action: /contact
    fields:
        - name: name
          id: name
          label: Name
          classes: form-control form-control-lg
          placeholder: Enter your name
          autocomplete: on
          type: text
          validate:
            required: true

        - name: email
          id: email
          classes: form-control form-control-lg
          label: Email
          placeholder: Enter your email address
          type: email
          validate:
            rule: email
            required: true

        - name: message
          label: Message
          classes: form-control form-control-lg
          size: long
          placeholder: Enter your message
          type: textarea
          validate:
            required: true

    buttons:
        - type: submit
          value: Submit
          class: btn btn-primary btn-block

    process:
        - email:
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.from }}"
              - "{{ form.value.email }}"
            subject: "[Feedback] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
        - save:
            fileprefix: feedback-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: Thank you for your feedback!
        - display: thankyou
```

`form.md` content in `_contact` modular:
```
---
menu: Contact us
cache_enable: false
---

## Let your customers contact you
Use the Contact module to let your customers contact you
```

But on page I see only this part of code in HTML elements:
```html
<form method="POST" action="/gravstrap-theme-simple-page-example/_contacts" name="">
	<div class="buttons">
	</div>
	<input type="hidden" value="be544dd90f65cfa87e50a248a2e5233d" 
name="form-nonce" id="form-nonce">

</form>
```

What I'm missed in my configuration?

**Comment by flaviocopes** [comment]
Forms in modular pages are managed differently: https://learn.getgrav.org/forms/forms/how-to-forms-in-modular-pages

**Comment by Sogl** [comment]
Mostly I used this manual and got this problem. I read all articles in forms category.

**Comment by flaviocopes** [comment]
It says "add the form header to the main modular page, modular.md", not in the modular page itself.

**Comment by Sogl** [comment]
It was mistake in issue description.
I pasted it here:
https://github.com/giansi/gravstrap-theme-skeleton/blob/master/pages/02.home_single/home_single_page.md

And `form.md` lays here:
https://github.com/giansi/gravstrap-theme-skeleton/tree/master/pages/02.home_single/_contacts

`contacts.md` deleted.

**Comment by flaviocopes** [comment]
It's quicker if you PM me your user/ folder to test I guess

**Comment by Sogl** [comment]
PM in gitter sended

**Comment by alexraj36** [comment]
We have same issue how did you fix this and  how to call modular in page template we have call like this

{% for module in page.find('/quick-contact').collection() %}
			{{ module.content }}
			     
		        {% endfor %} 
Please help me

**Comment by rhukster** [comment]
This issue should be addressed with the new multiform PR - https://github.com/getgrav/grav-plugin-form/pull/85

**Comment by rhukster** [comment]
I tested and can't replicate with shortcode plugin.
