### ISSUE TITLE
Add username to filename.

### ISSUE THREAD

**Issue by DavidABruce** [getgrav/grav-plugin-form#81]
I'm looking for a way to add the {{ grav.user.username }} to the filename or prefix of a form submission.
I was wondering if the form template could output something when the post is generated, was trying with the form.md "prefix:" initially. Sent here by Rhukster.

![filename](https://cloud.githubusercontent.com/assets/20596931/17056591/3d94b8d6-500c-11e6-8db0-f09056d1a582.jpg)

**Comment by flaviocopes** [comment]
You're adding 

```
 - save:
            fileprefix: userGoal-{{grav.user.username}}
```

in your form definition? I guess does not process the Twig, would be a good one to have.

**Comment by DavidABruce** [comment]
That's right, or things of that sort.

My idea was that the collected data might be easier to manage, recall or sort through if I could see usernames in the titles. Eventually it might even be good to make a folder system by user. But hopefully you can see what I was thinking when trying to do it.

**Comment by rhukster** [comment]
I will look at this tomorrow

**Comment by rhukster** [comment]
ok added in multi-form branch, for example:

```
filename: csvdata-{{ grav.user.username ?: 'guest' }}.txt
```

**Comment by krisak** [comment]
How to name after form textfield value?

Something like
`
 - save:
            fileprefix: posted-by-{{form.value.surname}}
`

**Comment by flaviocopes** [comment]
Twig is not currently processed for `save.fileprefix`

**Comment by flaviocopes** [comment]
Sorry, my bad - it IS supported (https://github.com/getgrav/grav-plugin-form/pull/85/commits/7f55cda20b6c605aca04cb3c42fd4e5abe1496dd) in the current `develop` branch of the plugin, not yet released.
