### ISSUE TITLE
Recatpcha still broken

### ISSUE THREAD

**Issue by ntsim** [getgrav/grav-plugin-form#83]
I've been playing around with Grav (and great work so far), but I've ran into a bug when using the Recaptcha for forms. I believe this is related to issues #51 and #54.

I get the following error:

```
Undefined index: recatpcha_secret
```

The culprit line is 120 in `form/form.php`:

```
'secret'   => isset($params['recaptcha_secret']) ? 
$params['recaptcha_secret'] : isset($params['recatpcha_secret']) ? 
$params['recatpcha_secret'] : $this->config->get('plugins.form.recaptcha.secret_key')
```

Originally I thought this might be a PHP7 issue, but it manifests in 5.6 as well. I believe the internals will not behave how you are expecting them to, and you actually have to wrap the second ternary operation in parens like so:

```
  'secret'   => isset($params['recaptcha_secret']) ? 
$params['recaptcha_secret'] : (isset($params['recatpcha_secret']) ? 
$params['recatpcha_secret'] : $this->config->get('plugins.form.recaptcha.secret_key')),
```

This should solve the issue. Just as a suggestion, I would advise against using _nested_ ternary operations as they reduce clarity of code and in cases like this, cause unexpected bugs. This isn't a great tradeoff just to save the few lines from using a declarative (but ugly) if/elseif/else block.

**Comment by rhukster** [comment]
I think you are correct. Can you please us it a pr? You can just edit directly in github.

**Comment by flaviocopes** [comment]
Thanks!
