### ISSUE TITLE
Missing Form Types

### ISSUE THREAD

**Issue by asirco** [getgrav/grav-plugin-form#87]
We need the ability to specify additional HTML5 form types. For example, Number and Tel.

When specifying Text and validate as number, it renders an input element of type text. If we want mobiles to offer a numerical keypad to aid user input, we need to be able to specify the relevant Number or Tel input types.

**Comment by rhukster** [comment]
I'll look at adding these types in the forms plugin. However it's very easy to just copy one of the other form fields like email into your themes template folder and modify it for telephone.

**Comment by mahagr** [comment]
All the types already exists in Gantry, btw.

**Comment by rhukster** [comment]
added
