### ISSUE TITLE
Plugin form v 2.0.1 breaks modular 'action' field processing

### ISSUE THREAD

**Issue by aitoraroza** [getgrav/grav-plugin-form#91]
Hi, 
I've just updated Form to v2.0.1 in a Grav website and contact form stopped working. It reloads itself with no form processing at all. Reverting back to v1.3.2 fixes the issue. Removing or setting an incorrect 'action' field and value in frontmatter gets a 404. I've seen in Grav documentation that Forms 2.0 allows to define form code directly to modular page instead of parent page. Guess there's some config involved but can't figure out what have changed.

Thanks in advance for your time.

**Comment by flaviocopes** [comment]
Mmm, looks like a regression! What's your modular form definition, can you paste it here and I'll check?

You read this https://learn.getgrav.org/forms/forms#modular-forms, right? Modular forms should work if defined in the modular child itself, no config involved.

**Comment by flaviocopes** [comment]
Just tested again, works fine to me

**Comment by aitoraroza** [comment]
Hello! Thanks for replying so quickly. I've also tried moving the form directly to modular child with no success at all. If I remove the 'action' field (was set as 'contact)', logically it takes the @self value of the module (eg. /contact/_childmodule) but hits an 404. ¿Something related to routes? 

I'm using a customized theme from getgrav.org (**Deliver**) but the form is just the original from that theme (except for labels).

[https://demo.getgrav.org/deliver-skeleton/contact](https://demo.getgrav.org/deliver-skeleton/contact)

Contact page at demo seems to work fine. But I've just downloaded full fresh skeleton package for deliver theme to test it at local php server. Not working anymore. Forms is already v2.0.1 in that package. Same behaviour.

Thanks again and have a great day!

**Comment by flaviocopes** [comment]
Mmm, reproduced the issue on the Deliver skeleton. Looking into it.

**Comment by flaviocopes** [comment]
Traced it to https://github.com/getgrav/grav-theme-deliver/commit/6ff958bf2fa7046ac0af1e4b07717b562ae295eb - can you simply remove the forms/ folder in the Deliver twig templates, and check if now it works?

**Comment by aitoraroza** [comment]
Hello Flavio, you found it. Form now works flawlessly. I wish I could have been of more help. 

Thanks for your time and work at Grav! Really really appreciated ;)

**Comment by flaviocopes** [comment]
Ok good! We can do a release today
