### ISSUE TITLE
v2.0.5 causes `Å Ä Ö` to produce extra margin between letters in plain markdown

### ISSUE THREAD

**Issue by jjui** [getgrav/grav-plugin-form#93]
ÅÄÖ will produce `Å Ä Ö` / `Göteborg` will be displayed as `Gö teborg`

Tested both copy plain text to form input and `md` + typing myself. 
Any idea why?

**Comment by flaviocopes** [comment]
Is that CSS margin or actual space? Have an example I can look at?

Also, where is this happening, in the form, or in the results once submitted?

**Comment by jjui** [comment]
Nothing wrapping or controling it by css, and there is no space either, just a margin. It is only in admin from inputs and were caused when updated to 2.0.5, and may be related to it. 

[And the image from admin.](http://www.tiikoni.com/tis/view/?id=9cb7f1c)

**Comment by jjui** [comment]
Aooh, think it is due to the encoding of the chars `åäö`, as when deleting the chars and typing them again seems to fix my problem. Will close this issue. TY @flaviocopes
