### ISSUE TITLE
multi-language 301 redirect breaking form submit

### ISSUE THREAD

**Issue by woutgg** [getgrav/grav-plugin-form#95]
On a site with translations enabled and with one form, the form does not submit data. Looking at the requests using chrome, it appeared that this is caused by a 301 redirect.
So the site URL looks like '.../nl/contact' but the form submits its POST data to '.../contact'. This results in the 301, causing the browser to just do a plain GET to '.../nl/contact' without any query.

Setting `include_default_lang` in system.yaml to false 'fixes' this issue because the locale component is taken out completely but that's not a real solution of course.

Am I missing something here? Otherwise I think grav should just accept URLs without locale in this case, and/or the form should post to a URL including the current locale.

**Comment by rhukster** [comment]
The new 2.0 versions of Forms was not really tested with forms in multi-languages.  We didn't have any test cases setup for that.  I will add that to the test setup, and get some fixes sorted. 

Thanks![](url)

**Comment by flaviocopes** [comment]
It was not related to 2.0 changes - to make it work in multilanguage sites, you needed to specify an action in the form definition which pointed to the page route, now I fixed this to make it automatic.

**Comment by SockFuzz** [comment]
https://github.com/getgrav/grav-plugin-form/issues/95

**Comment by mahagr** [comment]
Try Grav 1.7 beta, it has some fixes around this issue. If those aren't fixed, please open a new issue with steps to reproduce.
