### ISSUE TITLE
Submission of invalid email address causes Server Error

### ISSUE THREAD

**Issue by gitname** [getgrav/grav-plugin-form#99]
On the [demo site](https://demo.getgrav.org/soraarticle-skeleton/contact), when I submit the form with an invalid email address (e.g. `a`, as shown in screenshot **A**), the resulting page shows an error message indicating a Server Error occurred (as shown in screenshot **B**).

Screenshot **A**:

![screen shot 2016-11-03 at 12 27 24 am](https://cloud.githubusercontent.com/assets/7143133/19958439/5c33eed2-a15c-11e6-8142-115255eef99c.png)

Screenshot **B**:

![screen shot 2016-11-03 at 12 31 05 am](https://cloud.githubusercontent.com/assets/7143133/19958484/dda6d0e2-a15c-11e6-8fc9-80f3a7578b80.png)

I expected the resulting page to show the contact form again, along with a user-targeted error message (e.g. "The email address you entered was invalid."); as opposed to showing a server administrator-targeted message indicating a Server Error occurred.

**Comment by flaviocopes** [comment]
The email form field should use an `email` field, which checks for proper email formatting client-side, that's likely the issue. Seems to use a `text` field instead.
